import type { CuratedProblem } from '../types.ts';

export const dp1dProblems: CuratedProblem[] = [
  {
    slug: 'climbing-stairs', id: 70, title: 'Climbing Stairs', difficulty: 'Easy', pattern: 'dp-1d',
    insight: {
      q: 'Which recurrence counts the ways to reach step n?',
      options: [
        'ways(n) = ways(n − 1) + ways(n − 2), by the size of the last move',
        'ways(n) = 2 × ways(n − 1), since each step can be taken two ways',
        'ways(n) = n / 2 + 1, counting how many 2-steps fit',
        'ways(n) = ways(n − 1) + 1, adding the all-2-steps way',
      ],
      why: "Every way to reach step n ends with a 1-step move from n − 1 or a 2-step move from n − 2, and those two sets don't overlap. That's the Fibonacci recurrence, so two rolling variables are enough.",
    },
    time: ['O(n)', 'O(2ⁿ)', 'O(n²)', 'O(log n)'],
    space: ['O(1)', 'O(n)', 'O(2ⁿ)', 'O(n²)'],
    edgeCases: ['n = 1 (1 way)', 'n = 2 (2 ways)', 'Plain recursion without memoization is exponential'],
    approach: 'a = 1 (ways to stand on step 0), b = 1 (step 1). Repeat n − 1 times: (a, b) = (b, a + b). Return b.',
  },
  {
    slug: 'house-robber', id: 198, title: 'House Robber', difficulty: 'Medium', pattern: 'dp-1d',
    insight: {
      q: 'What is the recurrence for the best loot from the first i houses?',
      options: [
        'best(i) = max(best(i − 1), best(i − 2) + nums[i]): skip it or rob it',
        'Rob every other house, starting from whichever end gives more',
        'best(i) = best(i − 1) + nums[i], adding each house to the total',
        'Rob the most valuable houses first, skipping their neighbors',
      ],
      why: 'Robbing house i rules out house i − 1, so the best choice compares skipping i against robbing i on top of the best up to i − 2. Fixed alternation fails on [2, 1, 1, 2], whose answer is 4 = 2 + 2.',
    },
    time: ['O(n)', 'O(2ⁿ)', 'O(n²)', 'O(n log n)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['A single house', 'Two houses (take the larger)', 'Best houses not evenly spaced ([2, 1, 1, 2])'],
    approach: 'prev2 = prev1 = 0. For each x: cur = max(prev1, prev2 + x); prev2 = prev1; prev1 = cur. Return prev1.',
  },
  {
    slug: 'house-robber-ii', id: 213, title: 'House Robber II', difficulty: 'Medium', pattern: 'dp-1d',
    insight: {
      q: 'The houses form a circle. How do you reuse the linear House Robber solution?',
      options: [
        'Run it on [0, n − 2] and on [1, n − 1]; take the larger',
        'Run it once, then subtract the smaller of the first and last houses',
        'Run it on the whole array, since the circle only adds one adjacency',
        'Always skip house 0, since it touches both of its neighbors',
      ],
      why: "The first and last houses can't both be robbed, so any valid plan excludes at least one of them. Solving both cases covers every valid plan.",
    },
    time: ['O(n)', 'O(2ⁿ)', 'O(n²)', 'O(n log n)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['A single house (return it; both ranges would be empty)', 'Two houses', 'The best plan uses the last house'],
    approach: 'If n == 1 return nums[0]. Return max(robRange(0, n − 2), robRange(1, n − 1)), each using the House Robber rolling variables.',
  },
  {
    slug: 'decode-ways', id: 91, title: 'Decode Ways', difficulty: 'Medium', pattern: 'dp-1d',
    insight: {
      q: 'What is the recurrence for the number of decodings of the first i characters?',
      options: [
        'dp[i] = (one-digit ok ? dp[i−1] : 0) + (two-digit 10–26 ? dp[i−2] : 0)',
        'dp[i] = dp[i − 1] + dp[i − 2] always, just like Climbing Stairs',
        'dp[i] = 2 × dp[i − 1], since each digit can start or extend a letter',
        'Count the positions where the two-digit number there is between 10 and 26',
      ],
      why: 'The last letter is decoded from one digit (valid unless it is "0") or from two digits (valid for 10–26). Zeros are the trap: "06" has 0 decodings, "10" has exactly 1.',
    },
    time: ['O(n)', 'O(2ⁿ)', 'O(n²)', 'O(n log n)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(2ⁿ)'],
    edgeCases: ['A leading zero ("06" → 0)', '"10" and "20" (one decoding each)', '"30" or "100" (0 decodings)'],
    approach:
      "dp[0] = 1; dp[1] = s[0] != '0' ? 1 : 0. For i ≥ 2: add dp[i−1] if s[i−1] != '0'; add dp[i−2] if the number s[i−2..i−1] is in [10, 26]. Keep only the last two values for O(1) space.",
  },
  {
    slug: 'coin-change', id: 322, title: 'Coin Change', difficulty: 'Medium', pattern: 'dp-1d',
    insight: {
      q: 'What recurrence gives the fewest coins for amount a?',
      options: [
        'dp[a] = 1 + min over every coin c ≤ a of dp[a − c], with dp[0] = 0',
        'Take the largest coin that fits, then repeat on the remainder',
        'dp[a] = dp[a − 1] + 1, adding one coin per unit of amount',
        'Count the combinations that make a and take the smallest one',
      ],
      why: 'The last coin used is some c, leaving a − c to be made optimally. Greedy fails for coins {1, 3, 4} and amount 6 (4 + 1 + 1 instead of 3 + 3). Unreachable amounts stay at "infinity".',
    },
    vars: 'n = number of coin types, A = amount',
    time: ['O(n · A)', 'O(nᴬ)', 'O(A²)', 'O(n log A)'],
    space: ['O(A)', 'O(1)', 'O(n · A)', 'O(n)'],
    edgeCases: ['amount = 0 (0 coins)', 'An unreachable amount (−1)', 'Adding 1 to an "infinity" of Integer.MAX_VALUE overflows'],
    approach: 'dp[0] = 0 and dp[1..A] = A + 1 (as infinity). For a from 1 to A, for each coin c ≤ a: dp[a] = min(dp[a], dp[a − c] + 1). Return dp[A] > A ? −1 : dp[A].',
  },
  {
    slug: 'maximum-product-subarray', id: 152, title: 'Maximum Product Subarray', difficulty: 'Medium', pattern: 'dp-1d',
    alsoAccept: ['greedy'],
    insight: {
      q: "Why isn't a Kadane-style running maximum enough, and what fixes it?",
      options: [
        'Track both the max and the min product ending at each position',
        'Skip every negative number, since negatives only shrink the product',
        'Take the product of the whole array, since more factors mean more product',
        'Split at zeros and take the product of each whole segment',
      ],
      why: 'Multiplying by a negative swaps the roles of max and min, so the most negative product so far can become the best. At each x: newMax = max(x, x·max, x·min) and newMin = min(x, x·max, x·min), both from the old values. Whole segments fail with an odd number of negatives.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Zeros reset the product', 'An odd number of negatives', 'A single negative element'],
    approach: 'curMax = curMin = best = nums[0]. For each later x: from x, x·curMax and x·curMin take the new max and min (using the old values); best = max(best, curMax).',
  },
  {
    slug: 'word-break', id: 139, title: 'Word Break', difficulty: 'Medium', pattern: 'dp-1d',
    insight: {
      q: 'What does dp[i] mean, and how is it computed?',
      options: [
        'dp[i] = some j < i with dp[j] true and s[j..i) in the dictionary',
        'Greedily match the longest dictionary word at each position',
        'dp[i] = the number of dictionary words found inside s[0..i)',
        'Check that every dictionary word appears somewhere in s',
      ],
      why: 'A segmentation of a prefix ends with some word s[j..i) preceded by a segmentation of s[0..j). Greedy longest-match fails on "aaaaaaa" with ["aaaa", "aaa"]. Memoized DFS is the top-down version of the same idea.',
    },
    vars: 'n = length of s, L = longest word length, W = number of words',
    time: ['O(n · L²)', 'O(2ⁿ)', 'O(n · W)', 'O(W · L)'],
    space: ['O(n + W · L)', 'O(1)', 'O(2ⁿ)', 'O(n²)'],
    edgeCases: ['Reusing the same word many times', 'Greedy longest-match fails ("aaaaaaa", ["aaaa", "aaa"])', 'No segmentation exists'],
    approach:
      'Put the words in a HashSet; L = the longest word length. dp[0] = true. For i from 1 to n, for j from i − 1 down to max(0, i − L): if dp[j] and the set contains s.substring(j, i), set dp[i] = true and stop. Return dp[n].',
  },
  {
    slug: 'longest-increasing-subsequence', id: 300, title: 'Longest Increasing Subsequence', difficulty: 'Medium', pattern: 'dp-1d',
    alsoAccept: ['binary-search'],
    insight: {
      q: 'How do you get to O(n log n)?',
      options: [
        'Keep the smallest tail for each length; binary-search where x goes',
        'Sort the array and count the distinct values it contains',
        'Greedily extend the subsequence whenever the next number is larger',
        'dp[i] = dp[i − 1] + 1 whenever nums[i] > nums[i − 1]',
      ],
      why: 'The classic DP is O(n²): dp[i] = 1 + max dp[j] over j < i with nums[j] < nums[i]. Patience sorting improves it: a smaller tail for the same length is always better, so each number replaces the first tail ≥ it (or extends the list). tails.size() is the answer, although tails itself need not be a real subsequence.',
    },
    vars: 'n = length of nums; patience-sorting approach',
    time: ['O(n log n)', 'O(n²)', 'O(2ⁿ)', 'O(n)'],
    space: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Strictly decreasing input (answer 1)', 'Duplicates (strictly increasing, so use a lower bound)', 'A single element'],
    approach: 'tails = empty list. For each x, find the first index with tails[i] ≥ x; replace it with x, or append x if there is none. Return tails.size().',
  },
  {
    slug: 'partition-equal-subset-sum', id: 416, title: 'Partition Equal Subset Sum', difficulty: 'Medium', pattern: 'dp-1d',
    alsoAccept: ['dp-2d'],
    insight: {
      q: 'How do you decide whether the array splits into two halves with equal sums?',
      options: [
        'Odd total → no; else 0/1 knapsack for total / 2, target loop downward',
        'Sort the array, then assign elements alternately to the two halves',
        'Check whether the largest element equals the sum of all the others',
        'Repeatedly add the largest remaining element to the lighter half',
      ],
      why: 'Equal halves each sum to total / 2, so this is subset sum. In a 1-D boolean dp, iterating the target from high to low uses each number at most once. Greedy splitting fails on [3, 3, 2, 2, 2] (the answer is {3, 3} vs {2, 2, 2}).',
    },
    vars: 'n = length of nums, S = sum of nums',
    time: ['O(n · S)', 'O(2ⁿ)', 'O(n²)', 'O(S log n)'],
    space: ['O(S)', 'O(1)', 'O(n · S)', 'O(2ⁿ)'],
    edgeCases: ['An odd total (false immediately)', 'A single element', 'An element larger than total / 2 (false)'],
    approach: 'If the sum is odd return false; target = sum / 2; dp[0] = true. For each x, for t from target down to x: dp[t] |= dp[t − x]. Return dp[target].',
  },
];

export const dp2dProblems: CuratedProblem[] = [
  {
    slug: 'unique-paths', id: 62, title: 'Unique Paths', difficulty: 'Medium', pattern: 'dp-2d',
    insight: {
      q: 'Which recurrence counts the paths to cell (r, c)?',
      options: [
        'paths(r, c) = paths(r − 1, c) + paths(r, c − 1)',
        'paths(r, c) = r × c, one path per cell in the rectangle',
        'paths(r, c) = paths(r − 1, c − 1) + 1, moving diagonally',
        'paths(r, c) = 2^(r + c), two choices at every step',
      ],
      why: 'The last move into (r, c) came from above or from the left, and those sets of paths are disjoint. A single rolling row is enough. The closed form is C(m + n − 2, m − 1).',
    },
    vars: 'm × n grid; DP with a single rolling row',
    time: ['O(m · n)', 'O(2^(m+n))', 'O(m + n)', 'O((m · n)²)'],
    space: ['O(n)', 'O(m · n)', 'O(1)', 'O(2^(m+n))'],
    edgeCases: ['A 1×n or m×1 grid (1 path)', 'm = n = 1 (1 path)', 'Large grids (answer still fits per the constraints)'],
    approach: 'row = n ones. For each of the other m − 1 rows, for c from 1 to n − 1: row[c] += row[c − 1]. Return row[n − 1].',
  },
  {
    slug: 'longest-common-subsequence', id: 1143, title: 'Longest Common Subsequence', difficulty: 'Medium', pattern: 'dp-2d',
    insight: {
      q: 'What is the recurrence for dp[i][j] = LCS of text1[0..i) and text2[0..j)?',
      options: [
        'Match: dp[i−1][j−1] + 1; else max(dp[i−1][j], dp[i][j−1])',
        'Match: dp[i−1][j] + 1; else dp[i−1][j−1], skipping both characters',
        'dp[i][j] = dp[i−1][j−1] + 1 if the characters match, else dp[i−1][j−1]',
        'The number of distinct characters the two strings have in common',
      ],
      why: "Matching last characters can both be used, extending the LCS of the shorter prefixes. If they differ, at least one isn't in the LCS, so drop one of them and take the better result.",
    },
    vars: 'm, n = lengths of the two strings',
    time: ['O(m · n)', 'O(2^(m+n))', 'O(m + n)', 'O(m² · n²)'],
    space: ['O(m · n)', 'O(1)', 'O(m + n)', 'O(2^(m+n))'],
    edgeCases: ['No common characters (0)', 'Identical strings', 'One string is a subsequence of the other'],
    approach:
      'dp is (m + 1) × (n + 1) of zeros. For i, j ≥ 1: dp[i][j] = text1[i−1] == text2[j−1] ? dp[i−1][j−1] + 1 : max(dp[i−1][j], dp[i][j−1]). Return dp[m][n]. (A rolling row reduces space to O(min(m, n)).)',
  },
  {
    slug: 'longest-palindromic-substring', id: 5, title: 'Longest Palindromic Substring', difficulty: 'Medium', pattern: 'dp-2d',
    alsoAccept: ['two-pointers'],
    insight: {
      q: 'What is the simplest approach with O(n²) time and O(1) space?',
      options: [
        'Expand around all 2n − 1 centers while the ends match',
        'Reverse the string and take the longest common substring of the two',
        'Check every substring for being a palindrome and keep the longest',
        'Slide a window that shrinks whenever its two ends differ',
      ],
      why: 'Every palindrome has a center and expanding from it costs O(n), so all 2n − 1 centers take O(n²) with O(1) space. The dp[i][j] table (s[i] == s[j] && dp[i+1][j−1]) is also O(n²) time but uses O(n²) memory. Reverse-and-match is fooled by strings like "abacdfgdcaba".',
    },
    time: ['O(n²)', 'O(n³)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(1)', 'O(n²)', 'O(n)', 'O(log n)'],
    edgeCases: ['Even-length palindromes ("abba")', 'A single character', 'The whole string is a palindrome'],
    approach: "For each center, expand (i, i) and (i, i + 1) while s[l] == s[r], tracking the longest range found. (Manacher's algorithm is O(n) but rarely expected.)",
  },
  {
    slug: 'palindromic-substrings', id: 647, title: 'Palindromic Substrings', difficulty: 'Medium', pattern: 'dp-2d',
    alsoAccept: ['two-pointers'],
    insight: {
      q: 'How do you count all palindromic substrings in O(n²) time?',
      options: [
        'Expand around all 2n − 1 centers, counting each match',
        'Count the distinct characters, since each one is a palindrome',
        'Check every substring directly and count the palindromes',
        'Expand around each character only, counting each successful step',
      ],
      why: 'Each expansion step that still matches reveals exactly one new palindrome, so the counts add up in O(n²) time and O(1) space. Skipping the gaps misses every even-length palindrome. The dp[i][j] table gives the same count with O(n²) memory.',
    },
    time: ['O(n²)', 'O(n³)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(1)', 'O(n²)', 'O(n)', 'O(log n)'],
    edgeCases: ['All characters equal ("aaa" → 6)', 'Even-length palindromes', 'A single character (1)'],
    approach: 'For each center pair (i, i) and (i, i + 1): while l ≥ 0, r < n and s[l] == s[r], count++, l--, r++. Return count.',
  },
  {
    slug: 'coin-change-ii', id: 518, title: 'Coin Change II', difficulty: 'Medium', pattern: 'dp-2d',
    alsoAccept: ['dp-1d'],
    insight: {
      q: 'How do you count COMBINATIONS (not orderings) of coins that make the amount?',
      options: [
        'Coins in the outer loop, amounts inner: dp[a] += dp[a − coin]',
        'Amounts in the outer loop, coins inner: dp[a] += dp[a − coin]',
        'Run the fewest-coins DP and count the steps it takes',
        'Use the largest coins first and count the ways greedily',
      ],
      why: 'Finishing one coin type before the next builds every combination in one fixed coin order, so it is counted once. Swapping the loops counts [1, 2] and [2, 1] separately (orderings). dp[0] = 1: the empty combination.',
    },
    vars: 'n = number of coin types, A = amount',
    time: ['O(n · A)', 'O(nᴬ)', 'O(A²)', 'O(n log A)'],
    space: ['O(A)', 'O(1)', 'O(n · A)', 'O(n)'],
    edgeCases: ['amount = 0 (1 way)', 'No combination (0)', 'A coin larger than the amount'],
    approach: 'dp[0] = 1. For each coin c: for a from c to amount: dp[a] += dp[a − c]. Return dp[amount].',
  },
  {
    slug: 'target-sum', id: 494, title: 'Target Sum', difficulty: 'Medium', pattern: 'dp-2d',
    alsoAccept: ['dp-1d', 'backtracking'],
    insight: {
      q: 'How does this sign-assignment problem become subset sum?',
      options: [
        'Count subsets summing to (S + target) / 2 with 0/1 knapsack',
        'Give \'+\' to the largest numbers greedily until the target is reached',
        'It can only be solved by trying all 2ⁿ sign assignments',
        'Count the subsets whose sum equals the target itself',
      ],
      why: 'Rearranging gives sum(P) = (S + target) / 2, which must be a non-negative integer, so the task counts subsets with that sum. A 1-D dp iterating downward counts them in O(n · S). Memoized DFS over (index, running sum) also works.',
    },
    vars: 'n = length of nums, S = sum of nums',
    time: ['O(n · S)', 'O(2ⁿ)', 'O(n²)', 'O(S²)'],
    space: ['O(S)', 'O(1)', 'O(n · S)', 'O(2ⁿ)'],
    edgeCases: ['(S + target) odd or negative (0 ways)', '|target| > S (0 ways)', 'Zeros in nums (each one doubles the count)'],
    approach: 'If |target| > S or (S + target) is odd, return 0. goal = (S + target) / 2; dp[0] = 1; for each x, for t from goal down to x: dp[t] += dp[t − x]. Return dp[goal].',
  },
  {
    slug: 'best-time-to-buy-and-sell-stock-with-cooldown', id: 309, title: 'Best Time to Buy and Sell Stock with Cooldown', difficulty: 'Medium', pattern: 'dp-2d',
    alsoAccept: ['dp-1d'],
    insight: {
      q: 'Which states capture the cooldown rule?',
      options: [
        'Three states per day: holding, just sold, and resting',
        'Buy at every local minimum and sell at every local maximum',
        'A single state per day: the best profit made so far',
        'Only trade on every other day so the cooldown is always respected',
      ],
      why: "hold = max(hold, rest − price); sold = hold + price; rest = max(rest, sold), all from yesterday's values. Selling forces the next day into cooldown, which the separate sold state encodes. Buying at every local minimum ignores the cooldown.",
    },
    vars: 'n = number of days',
    time: ['O(n)', 'O(n²)', 'O(2ⁿ)', 'O(n log n)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(2ⁿ)'],
    edgeCases: ['A single day (0)', 'Prices only fall (0)', "Selling one day and buying the next isn't allowed"],
    approach:
      "hold = −∞, sold = 0, rest = 0. For each price, compute from the previous day's values: newHold = max(hold, rest − price), newSold = hold + price, newRest = max(rest, sold). Return max(sold, rest).",
  },
  {
    slug: 'edit-distance', id: 72, title: 'Edit Distance', difficulty: 'Medium', pattern: 'dp-2d',
    insight: {
      q: 'What is the recurrence for dp[i][j] = edits to turn word1[0..i) into word2[0..j)?',
      options: [
        'Match: dp[i−1][j−1]; else 1 + min(insert, delete, replace)',
        'The difference between the lengths of the two words',
        'The number of positions where the two words differ',
        '1 + dp[i−1][j−1] always, since every step edits one character',
      ],
      why: 'The last operation either keeps a matching character or is an insert, a delete or a replace, each leaving a smaller subproblem. Base cases: dp[i][0] = i deletions and dp[0][j] = j insertions.',
    },
    vars: 'm, n = lengths of the two words',
    time: ['O(m · n)', 'O(3^(m+n))', 'O(m + n)', 'O(m² · n²)'],
    space: ['O(m · n)', 'O(1)', 'O(m + n)', 'O(3^(m+n))'],
    edgeCases: ['One word empty (answer = the other length)', 'Identical words (0)', 'Completely different words'],
    approach:
      'dp[i][0] = i, dp[0][j] = j. For i, j ≥ 1: if word1[i−1] == word2[j−1] then dp[i][j] = dp[i−1][j−1]; else dp[i][j] = 1 + min(dp[i−1][j], dp[i][j−1], dp[i−1][j−1]). Return dp[m][n].',
  },
  {
    slug: 'longest-increasing-path-in-a-matrix', id: 329, title: 'Longest Increasing Path in a Matrix', difficulty: 'Hard', pattern: 'dp-2d',
    alsoAccept: ['graph-traversal', 'topological-sort'],
    insight: {
      q: 'Why can you memoize a DFS here without a visited set?',
      options: [
        'Moves strictly increase, so no path can revisit a cell',
        'Because a BFS from the smallest cell visits every cell only once',
        'Because every row and column of the matrix is sorted',
        'You cannot: every path from every cell has to be explored',
      ],
      why: "Strictly increasing moves can't form a cycle, so a cell's longest path never depends on itself: each cell is computed once and reused. A topological sort that peels cells by out-degree also works.",
    },
    vars: 'm × n matrix',
    time: ['O(m · n)', 'O(4^(m·n))', 'O((m · n)²)', 'O(m · n · log(m · n))'],
    space: ['O(m · n)', 'O(1)', 'O(m + n)', 'O((m · n)²)'],
    edgeCases: ['All values equal (answer 1)', 'A 1×1 matrix', 'A long snake-shaped increasing path'],
    approach: 'dfs(r, c): if memo[r][c] > 0 return it; best = 1; for each neighbor with a larger value, best = max(best, 1 + dfs(neighbor)); store and return best. Answer = max of dfs over all cells.',
  },
];

export const trieProblems: CuratedProblem[] = [
  {
    slug: 'implement-trie-prefix-tree', id: 208, title: 'Implement Trie (Prefix Tree)', difficulty: 'Medium', pattern: 'trie',
    insight: {
      q: 'What must each node store to support both search and startsWith?',
      options: [
        'Child links by character, plus an end-of-word flag',
        'The full list of words that pass through the node',
        'Only its own character, since the path spells the word',
        'A count of words ending below it, without child links',
      ],
      why: 'Child links let you walk a prefix in O(L). The end flag separates a stored word from a mere prefix: after inserting "apple", search("app") must be false while startsWith("app") is true.',
    },
    vars: 'L = length of the word or prefix, N = total characters inserted',
    time: ['O(L) per operation', 'O(N) per operation', 'O(L²) per operation', 'O(log N) per operation'],
    space: ['O(26 · N)', 'O(1)', 'O(L)', 'O(N²)'],
    edgeCases: ['Searching for a prefix of a stored word ("app" after "apple")', 'Inserting the same word twice', 'A word that is a prefix of another word'],
    approach: 'Node = Node[26] children + boolean isWord. insert walks/creates children and sets isWord. search walks and returns node != null && node.isWord. startsWith walks and returns node != null.',
  },
  {
    slug: 'design-add-and-search-words-data-structure', id: 211, title: 'Design Add and Search Words Data Structure', difficulty: 'Medium', pattern: 'trie',
    alsoAccept: ['backtracking'],
    insight: {
      q: "How do you support '.' (matches any letter) in search?",
      options: [
        'A trie; on \'.\', try every existing child recursively',
        'A HashSet of words, comparing each word character by character',
        'Replace every \'.\' with \'a\' and look the word up directly',
        'Store every wildcard variant of each word when it is added',
      ],
      why: 'The trie shares prefixes, so a search branches only at wildcards and prunes as soon as a child is missing. Comparing against every stored word is O(W · L) per search, and storing every wildcard variant costs 2^L entries per word.',
    },
    vars: 'L = query length, d = dots in the query, W = stored words, N = total characters inserted',
    time: ['O(26^d · L) per search', 'O(L) per search, even with dots', 'O(2^L) per search', 'O(W · L²) per search'],
    space: ['O(N)', 'O(1)', 'O(2^L)', 'O(W²)'],
    edgeCases: ['A query made only of dots', 'A query longer than every stored word', 'A dot in the last position'],
    approach: "search(word, i, node): if i == word.length() return node.isWord. If word[i] == '.', return true if any non-null child succeeds with i + 1; otherwise follow the matching child (false if it is null).",
  },
  {
    slug: 'replace-words', id: 648, title: 'Replace Words', difficulty: 'Medium', pattern: 'trie',
    alsoAccept: ['hashing'],
    insight: {
      q: "How do you find each word's shortest root efficiently?",
      options: [
        'Roots in a trie; walk each word and stop at the first root end',
        'For each word, test every root with startsWith and keep the first hit',
        'Sort the roots by length and use the longest root that matches',
        'Replace each word with its first letter, the shortest possible root',
      ],
      why: 'Walking the trie along a word visits its prefixes from shortest to longest, so the first end-of-root flag is the shortest root, and each word costs at most its own length. Testing every root per word is far slower, and the problem wants the SHORTEST root.',
    },
    vars: 'N = total length of the sentence, R = total length of the roots',
    time: ['O(N + R)', 'O(N · R)', 'O(N²)', 'O(R log R + N²)'],
    space: ['O(R)', 'O(1)', 'O(N · R)', 'O(N²)'],
    edgeCases: ['A word with no root (keep it unchanged)', 'Several roots match (use the shortest)', 'A root equal to the whole word'],
    approach: 'Build a trie from the roots. For each word, walk the trie: if a node ends a root, emit that prefix; if a child is missing, emit the word unchanged. Join the results with spaces.',
  },
  {
    slug: 'word-search-ii', id: 212, title: 'Word Search II', difficulty: 'Hard', pattern: 'trie',
    alsoAccept: ['backtracking'],
    insight: {
      q: 'How do you search the board for many words at once?',
      options: [
        'A trie of the words; one DFS per cell following trie children',
        'Run the single-word Word Search separately for every word',
        'BFS from each cell, collecting every string up to the longest word length',
        'Sort the words and binary-search every string found on the board',
      ],
      why: 'The trie lets one DFS test every word sharing the current prefix, and a missing child prunes the path immediately. Storing each word at its end node, clearing it once found and pruning emptied branches avoids duplicates and repeated work.',
    },
    vars: 'm × n board, L = longest word length, W = number of words, K = total letters in all words',
    time: ['O(m · n · 3^L)', 'O(W · m · n · 3^L)', 'O(m · n · W)', 'O(W · L)'],
    space: ['O(K)', 'O(1)', 'O(m · n · K)', 'O(3^L)'],
    edgeCases: ['The same word reachable by several paths (report it once)', 'Words that are prefixes of other words', 'A cell cannot be reused within one word'],
    approach:
      "Insert every word into a trie, storing the word at its end node. For each cell, dfs(r, c, node): follow the child for board[r][c]; if null return; if it holds a word, record and clear it; mark the cell '#', explore four neighbors, restore it, and prune the child if it became empty.",
  },
];

export const bitProblems: CuratedProblem[] = [
  {
    slug: 'single-number', id: 136, title: 'Single Number', difficulty: 'Easy', pattern: 'bit-manipulation',
    insight: {
      q: 'How do you find the single element in O(n) time and O(1) space?',
      options: [
        'XOR everything: pairs cancel, leaving the single one',
        'Sort the array and compare each element with its neighbors',
        'Add and remove values in a HashSet; the one left is the answer',
        'Sum everything and divide by 2, since pairs double their values',
      ],
      why: 'XOR is commutative and associative, with a ^ a = 0 and a ^ 0 = a, so every pair cancels in any order and only the single value remains. A set also works but uses O(n) space; sorting is O(n log n).',
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['A one-element array', 'Negative numbers', 'The single number is 0'],
    approach: 'x = 0; for each n: x ^= n. Return x.',
  },
  {
    slug: 'number-of-1-bits', id: 191, title: 'Number of 1 Bits', difficulty: 'Easy', pattern: 'bit-manipulation',
    insight: {
      q: 'What is an efficient way to count the set bits?',
      options: [
        'Repeat n &= n − 1, counting iterations',
        'Divide by 10 repeatedly and count the digits that are 1',
        'Compute floor(log₂ n) + 1, the number of binary digits',
        'Return n % 2, the value of the lowest bit',
      ],
      why: 'n − 1 flips the lowest set bit and everything below it, so n & (n − 1) removes exactly one set bit per iteration: the loop runs once per 1-bit. Checking n & 1 and shifting with >>> also works, in up to 32 iterations. log₂ gives the bit LENGTH, not the count.',
    },
    vars: 'n = the input value, k = number of set bits (≤ 32)',
    time: ['O(k)', 'O(n)', 'O(n log n)', 'O(√n)'],
    space: ['O(1)', 'O(k)', 'O(log n)', 'O(n)'],
    edgeCases: ['n = 1', 'n = 2³¹ − 1 (31 set bits)', 'Powers of two (exactly one set bit)'],
    approach: 'count = 0; while n != 0: n &= n − 1; count++. Return count. (Integer.bitCount is the built-in.)',
  },
  {
    slug: 'counting-bits', id: 338, title: 'Counting Bits', difficulty: 'Easy', pattern: 'bit-manipulation',
    alsoAccept: ['dp-1d'],
    insight: {
      q: 'How do you get the bit counts of 0..n in O(n)?',
      options: [
        'Reuse a smaller answer: bits[i] = bits[i >> 1] + (i & 1)',
        'Count the bits of every number from scratch with a loop',
        'bits[i] = bits[i − 1] + 1, since each number adds one',
        'bits[i] = i % 2, since only the last bit changes',
      ],
      why: "i >> 1 drops i's last bit and is smaller than i, so its count is already known; add back the dropped bit with (i & 1). bits[i] = bits[i & (i − 1)] + 1 works too. Counting from scratch costs O(n log n).",
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['n = 0 (answer [0])', 'Powers of two (count 1)', 'n = 1'],
    approach: 'bits = new int[n + 1]. For i from 1 to n: bits[i] = bits[i >> 1] + (i & 1). Return bits.',
  },
  {
    slug: 'missing-number', id: 268, title: 'Missing Number', difficulty: 'Easy', pattern: 'bit-manipulation',
    alsoAccept: ['hashing'],
    insight: {
      q: 'How do you find the missing number in O(n) time and O(1) space?',
      options: [
        'XOR all indices 0..n with all values; the leftover is missing',
        'Sort the array and scan for the first gap between neighbors',
        'Put the values in a HashSet and probe 0..n for the absent one',
        'Return n, since the largest number is the one usually left out',
      ],
      why: "Every present number cancels its matching index under XOR, leaving the missing one. The sum formula works too (Java int overflow wraps and still gives the right difference). A set uses O(n) space and sorting costs O(n log n).",
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['The missing number is 0', 'The missing number is n', 'n = 1'],
    approach: 'x = n. For i from 0 to n − 1: x ^= i ^ nums[i]. Return x.',
  },
  {
    slug: 'sum-of-two-integers', id: 371, title: 'Sum of Two Integers', difficulty: 'Medium', pattern: 'bit-manipulation',
    insight: {
      q: 'How do you add two integers without + or −?',
      options: [
        'Loop: a ^ b is the sum without carries, (a & b) << 1 the carry',
        'Increment a by one, b times, using a loop counter',
        'Return a | b, which sets every bit that either number has',
        'Return (a ^ b) << 1, shifting the partial sum into place',
      ],
      why: "XOR adds each bit position ignoring carries; AND marks positions where both bits are 1, which carry into the next position. Feeding the carry back in until none remain completes the sum, and in Java's 32-bit two's complement it works for negatives too.",
    },
    vars: 'a, b are 32-bit ints',
    time: ['O(1) (at most 32 iterations)', 'O(a + b)', 'O(log(a + b))', 'O(max(a, b))'],
    space: ['O(1)', 'O(a + b)', 'O(log(a + b))', 'O(max(a, b))'],
    edgeCases: ["Negative numbers (two's complement)", 'a or b is 0', 'Results near the int limits'],
    approach: 'while (b != 0) { int carry = (a & b) << 1; a ^= b; b = carry; } return a.',
  },
];
