import type { CuratedProblem } from '../types.ts';

// Third pass: the most-reported interview classics that company data showed were missing from the bank.
// Convention for every quiz: the FIRST option is the correct one (the server shuffles).

export const classicProblems: CuratedProblem[] = [
  {
    slug: 'longest-common-prefix', id: 14, title: 'Longest Common Prefix', difficulty: 'Easy', pattern: 'two-pointers', alsoAccept: ['trie', 'binary-search'],
    brute: { text: 'Generate every prefix of the first string and test it against every other string.', time: ['O(n·m²)', 'O(n·m)', 'O(m log n)', 'O(n + m)'] },
    insight: {
      q: 'How do you find the longest prefix that every string shares?',
      options: [
        'Scan column by column, comparing every string\'s character at index i with the first string\'s, until one differs',
        'Sort the strings by length and return the shortest one, since no common prefix can ever be longer than that one',
        'Put every prefix of every string into one shared set and return the longest prefix that appears in that set',
        'Find the longest common substring of the first two strings, then check it against each of the remaining strings',
      ],
      why: 'A common prefix of all strings is also a prefix of the first one, so you only ever need to walk the first string and compare column by column, stopping at the first column where any string differs or runs out. The shortest string only bounds the answer; a substring need not start at index 0.',
    },
    vars: 'n = number of strings, m = length of the shortest string',
    time: ['O(n·m)', 'O(n·m²)', 'O(m log n)', 'O(n + m)'],
    space: ['O(1)', 'O(n)', 'O(m)', 'O(n·m)'],
    edgeCases: ['An empty string in the array makes the answer ""', 'A single string is its own prefix', 'No common first letter'],
    approach: 'For i from 0 up to the first string\'s length: take c = strs[0][i]; if any other string is shorter than i + 1 or has a different character at i, return strs[0].substring(0, i). If the loop finishes, the whole first string is the prefix.',
  },
  {
    slug: 'palindrome-number', id: 9, title: 'Palindrome Number', difficulty: 'Easy', pattern: 'two-pointers',
    brute: { text: 'Convert the number to a string and compare it with its reverse.', time: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'] },
    insight: {
      q: 'How do you test a palindrome without converting the number to a string?',
      options: [
        'Reverse only the second half of the digits and compare it with the first half, stopping when the halves meet',
        'Compare the first digit with the last by dividing by 10 repeatedly, never looking at any digit in the middle',
        'Add up the digits and check that the sum is even, since a symmetric number has digits that pair up evenly',
        'Check only that the number is divisible by 11, since every palindrome has an even number of digits in it',
      ],
      why: 'Peeling digits off the end with % 10 and / 10 and building the reverse stops after half the digits: when the reversed half is no longer smaller than what remains, compare the two (dropping the middle digit for odd lengths). That avoids the overflow a full reverse can cause.',
    },
    vars: 'n = the value of the number (it has about log₁₀ n digits)',
    time: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'],
    space: ['O(1)', 'O(log n)', 'O(n)', 'O(√n)'],
    edgeCases: ['Negative numbers are never palindromes', 'A number ending in 0 can only be a palindrome if it is 0', 'Odd digit counts: drop the middle digit when comparing'],
    approach: 'If x < 0, or x ends in 0 and is not 0, return false. Build rev from the last digits of x while x > rev (rev = rev·10 + x % 10; x /= 10). The number is a palindrome if x == rev (even length) or x == rev / 10 (odd length).',
  },
  {
    slug: 'spiral-matrix', id: 54, title: 'Spiral Matrix', difficulty: 'Medium', pattern: 'two-pointers',
    brute: { text: 'Walk the grid with a visited matrix, turning clockwise whenever the next cell is out of bounds or visited.', time: ['O(m·n)', 'O(m·n·(m + n))', 'O(m + n)', 'O((m·n)²)'] },
    insight: {
      q: 'How do you read a matrix in clockwise spiral order without a visited array?',
      options: [
        'Keep four shrinking boundaries (top, bottom, left, right); walk each edge, then move that boundary inward',
        'Sort the cells by their distance from the centre and read them from the outermost ring towards the middle of the grid',
        'Read every row left to right, then every column top to bottom, and drop the cells that were already seen before',
        'Use a stack of cells, pushing the neighbours clockwise and popping the next one, as in a depth-first search of the grid',
      ],
      why: 'After each edge is read, that whole row or column is finished, so the matching boundary moves inward by one. The walk ends when the boundaries cross. Two checks (top ≤ bottom, left ≤ right) before the bottom and left edges stop single rows and columns being read twice.',
    },
    vars: 'm × n = the size of the matrix',
    time: ['O(m·n)', 'O(m·n·(m + n))', 'O(m + n)', 'O((m·n)²)'],
    space: ['O(1)', 'O(m·n)', 'O(m + n)', 'O(min(m, n))'],
    edgeCases: ['A single row or a single column', 'Non-square matrices, where the inner boundaries cross early', 'A 1×1 matrix'],
    approach: 'Let top = 0, bottom = m − 1, left = 0, right = n − 1. While top ≤ bottom and left ≤ right: read the top row left to right and top++; the right column top to bottom and right−−; if top ≤ bottom the bottom row right to left and bottom−−; if left ≤ right the left column bottom to top and left++. The output list is not counted as extra space.',
  },
  {
    slug: 'merge-sorted-array', id: 88, title: 'Merge Sorted Array', difficulty: 'Easy', pattern: 'two-pointers',
    brute: { text: 'Append nums2 to nums1 and sort the whole array.', time: ['O((m + n) log(m + n))', 'O(m + n)', 'O(m·n)', 'O(n log n)'] },
    insight: {
      q: 'nums1 has spare room at its end. How do you merge in place without overwriting values you still need?',
      options: [
        'Fill nums1 from the back with the larger of the two current last elements, so no unread value is overwritten',
        'Fill nums1 from the front with the smaller element, shifting the rest of nums1 to the right whenever it is needed',
        'Copy nums1 into a temporary array first and merge forwards, because merging in place is not possible at all here',
        'Insert each element of nums2 into nums1 using binary search for its position and a shift of the larger values',
      ],
      why: 'The free space is at the end, and the largest values belong there, so writing from the back never lands on an element that has not been read yet. Each element moves exactly once. Front-filling would overwrite unread values and need shifting.',
    },
    vars: 'm = elements in nums1, n = elements in nums2',
    time: ['O(m + n)', 'O(m·n)', 'O((m + n) log(m + n))', 'O(n)'],
    space: ['O(1)', 'O(m)', 'O(m + n)', 'O(n)'],
    edgeCases: ['m = 0: copy all of nums2', 'n = 0: nothing to do', 'Every element of nums2 is smaller than nums1'],
    approach: 'Use i = m − 1, j = n − 1, k = m + n − 1. While j ≥ 0: if i ≥ 0 and nums1[i] > nums2[j] put nums1[i−−] at nums1[k−−], else put nums2[j−−] at nums1[k−−]. When nums2 is exhausted the rest of nums1 is already in place.',
  },
  {
    slug: 'string-compression', id: 443, title: 'String Compression', difficulty: 'Medium', pattern: 'two-pointers',
    brute: { text: 'Build the compressed text in a StringBuilder, then copy it back into the array.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'How do you compress runs of repeated characters in place, writing the result into the same array?',
      options: [
        'A read pointer measures each run; the write pointer behind it writes the character and then the digits of the count',
        'Count every character with a HashMap first, then write each distinct character followed by its total count overall',
        'Sort the array so that equal characters are together, then write each character with its count over the sorted data',
        'Build the compressed string, then copy it in from the end of the array so that nothing is overwritten too early',
      ],
      why: 'The compressed form is never longer than the original, so a write pointer can never overtake the read pointer. Runs are consecutive characters, so a global count or a sort would merge runs that are not adjacent and change the answer.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(26)'],
    edgeCases: ['A run of length 1 is written without a count', 'Counts of 10 or more become several digit characters', 'A one-character array'],
    approach: 'Walk with read index i; find the end j of the run of chars[i]. Write chars[i] at write index w. If the run length is more than 1, write each digit of the length at the next positions. Continue from j. Return w.',
  },
  {
    slug: 'majority-element', id: 169, title: 'Majority Element', difficulty: 'Easy', pattern: 'hashing', alsoAccept: ['greedy'],
    brute: { text: 'For each element, count how often it occurs by scanning the whole array again.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'One value appears more than n/2 times. What is the fastest way to find it?',
      options: [
        'Count frequencies in a HashMap and return the value whose count is above n/2',
        'Take the middle element of the array as it arrives, since a majority element must always sit in the centre',
        'Return the largest value in the array, because a majority element wins every comparison it takes part in',
        'XOR every element together; the majority element survives while all the other values cancel out in pairs',
      ],
      why: 'A frequency map answers it in one pass. The middle element only works on a sorted array, the maximum is unrelated, and XOR cancels pairs of equal values, which does not isolate a majority.',
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    space: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    edgeCases: ['A single element', 'The majority has exactly n/2 + 1 occurrences', 'Negative numbers'],
    approach: 'Count each value in a HashMap and return the first whose count exceeds n/2. (Alternative: Boyer–Moore voting keeps a candidate and a counter, adding for matches and subtracting otherwise, in O(n) time and O(1) space.)',
  },
  {
    slug: 'rotate-image', id: 48, title: 'Rotate Image', difficulty: 'Medium', pattern: 'two-pointers',
    brute: { text: 'Allocate a second matrix and write every cell to its rotated position.', time: ['O(n²)', 'O(n)', 'O(n³)', 'O(n log n)'] },
    insight: {
      q: 'How do you rotate an n×n matrix 90° clockwise in place?',
      options: [
        'Transpose the matrix (swap across the main diagonal), then reverse each row',
        'Reverse each row and then reverse the order of the columns, which together make a quarter turn of the matrix',
        'Sort each row and each column independently, which moves every value to its rotated position in the grid',
        'Swap every cell with the cell directly opposite it through the centre once, for the whole matrix at once',
      ],
      why: 'A clockwise quarter turn is a transpose followed by a mirror of each row. Reversing rows and columns is a half turn (180°), and sorting or point-reflecting through the centre do not map cells to their rotated place.',
    },
    vars: 'n = side length (the matrix has n² cells)',
    time: ['O(n²)', 'O(n)', 'O(n³)', 'O(n² log n)'],
    space: ['O(1)', 'O(n²)', 'O(n)', 'O(log n)'],
    edgeCases: ['A 1×1 matrix', 'Odd sizes leave the centre cell where it is', 'Swap each symmetric pair once, not twice'],
    approach: 'For i < j swap m[i][j] with m[j][i] (transpose). Then reverse every row. Both passes touch each cell a constant number of times, in place.',
  },
  {
    slug: 'integer-to-roman', id: 12, title: 'Integer to Roman', difficulty: 'Medium', pattern: 'greedy',
    brute: { text: 'Subtract 1 repeatedly, appending I each time, then rewrite groups such as IIII into IV.', time: ['O(num)', 'O(1)', 'O(log num)', 'O(num²)'] },
    insight: {
      q: 'How do you convert a number to Roman numerals, including the subtractive forms like IV and CM?',
      options: [
        'Greedy over a value table from 1000 down to 1 that includes 900, 400, 90, 40, 9 and 4, appending while it fits',
        'Convert each decimal digit on its own with if-else branches for 0 to 9, then reverse the whole string at the end of it',
        'Build the numeral in binary with only I and V, then replace groups of symbols with their larger equivalents later',
        'Use dynamic programming, taking the fewest symbols needed for each smaller number before the next larger number',
      ],
      why: 'Putting the six subtractive values into the table makes the greedy choice correct: at each step the largest value that fits is always the next symbol group. The table has a fixed 13 entries, and each can repeat only a bounded number of times, so the work is constant.',
    },
    time: ['O(1)', 'O(log num)', 'O(num)', 'O(num²)'],
    space: ['O(1)', 'O(log num)', 'O(num)', 'O(num²)'],
    edgeCases: ['The subtractive forms 4, 9, 40, 90, 400 and 900', '3999 is the largest input', 'Thousands use only M (up to MMM)'],
    approach: 'Keep parallel arrays values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1] and symbols = [M, CM, D, CD, C, XC, L, XL, X, IX, V, IV, I]. For each entry, while num ≥ value append the symbol and subtract. The input is at most 3999, so the loops are bounded.',
  },
  {
    slug: 'roman-to-integer', id: 13, title: 'Roman to Integer', difficulty: 'Easy', pattern: 'hashing',
    brute: { text: 'Replace each subtractive pair (IV, IX, XL…) with a temporary symbol, then sum the values in a second pass.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'A smaller symbol before a larger one is subtracted. How do you total the value in one pass?',
      options: [
        'Look up each symbol in a map; if its value is less than the next symbol\'s value subtract it, otherwise add it',
        'Process the string from the right and always add the value, since subtraction only affects the leftmost symbol',
        'Add every symbol\'s value, then subtract the number of subtractive pairs found in the string from the total',
        'Split the string at every I, V and X to get chunks and evaluate each chunk with its own fixed lookup table',
      ],
      why: 'Comparing a symbol with its right neighbour decides add or subtract on the spot, so one left-to-right pass with a 7-entry lookup is enough. Adding everything and subtracting a count is wrong because a subtractive pair must lose twice the smaller value, not 1.',
    },
    vars: 'n = length of the string (the symbol table has a fixed 7 entries)',
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    space: ['O(1)', 'O(n)', 'O(26)', 'O(log n)'],
    edgeCases: ['Subtractive pairs: IV, IX, XL, XC, CD, CM', 'A single symbol', 'MCMXCIV, with several subtractive pairs'],
    approach: 'Map I, V, X, L, C, D, M to their values. For i in 0..n−1: if i + 1 < n and value(s[i]) < value(s[i+1]) subtract value(s[i]) from the total, otherwise add it.',
  },
  {
    slug: 'remove-duplicates-from-sorted-array', id: 26, title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy', pattern: 'two-pointers',
    brute: { text: 'Copy the distinct values into a HashSet or a new list, then write them back to the front of the array.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'The array is sorted and must be de-duplicated in place. What is the pattern?',
      options: [
        'A write pointer marks the end of the unique prefix; a read pointer copies a value only if it differs from the last kept',
        'Remove each duplicate by shifting the whole tail of the array one step to the left every time that one is found',
        'Insert every value into a HashSet, sort the set again, and then trim the array down to the size of that set',
        'Binary-search for the next value that differs from the current one and swap it into the next free position in the array',
      ],
      why: 'Because the array is sorted, duplicates are adjacent, so comparing each value with the last kept value is enough. Each element is read once and written at most once. Shifting the tail for every duplicate is O(n²).',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['An empty or one-element array', 'All elements equal', 'No duplicates at all'],
    approach: 'If nums is empty return 0. Let w = 1. For r from 1: if nums[r] != nums[w − 1] then nums[w++] = nums[r]. Return w, the length of the unique prefix.',
  },
  {
    slug: 'next-permutation', id: 31, title: 'Next Permutation', difficulty: 'Medium', pattern: 'two-pointers',
    brute: { text: 'Generate all permutations in lexicographic order and pick the one after the given array.', time: ['O(n!·n)', 'O(n)', 'O(n log n)', 'O(n²)'] },
    insight: {
      q: 'How do you find the next larger arrangement in place?',
      options: [
        'Find the rightmost ascent a[i] < a[i+1], swap a[i] with the next larger value on its right, then reverse that suffix',
        'Swap the last two elements, and if they are already in descending order swap the two before them instead, and so on',
        'Sort the suffix after the first element that has any larger element somewhere to its right in ascending order',
        'Add one to the last element and carry the overflow leftwards, as when adding one to a number written in digits',
      ],
      why: 'The longest descending suffix is already the largest possible ordering of those elements, so the pivot is the element just before it. Swapping the pivot with the next larger value in the suffix raises the prefix minimally, and reversing the (descending) suffix makes it the smallest possible.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(n!)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['A fully descending array wraps around to the smallest (just reverse it)', 'Duplicate values', 'A single element'],
    approach: 'Scan from the right for the first i with nums[i] < nums[i+1]. If one exists, scan from the right for the first j with nums[j] > nums[i] and swap them. Then reverse nums[i+1..end]. Without such an i, reverse the whole array.',
  },
  {
    slug: 'minimum-absolute-difference', id: 1200, title: 'Minimum Absolute Difference', difficulty: 'Easy', pattern: 'two-pointers',
    brute: { text: 'Compare every pair of elements and keep the pairs with the smallest difference.', time: ['O(n²)', 'O(n log n)', 'O(n)', 'O(n³)'] },
    insight: {
      q: 'Which pairs can possibly have the minimum absolute difference?',
      options: [
        'Only neighbours in sorted order: sort, find the smallest adjacent gap, then list every adjacent pair with that gap',
        'The pair formed by the smallest and the largest element, since that pair spans the whole range of the values given',
        'Pairs that sit within a fixed small distance of each other in the original unsorted order of the array of numbers',
        'Use a HashSet and look up value ± 1 for each element, since the minimum difference is always exactly one here',
      ],
      why: 'If two values have another value between them in sorted order, that value is closer to at least one of them, so a minimal pair is always adjacent once sorted. One pass over the adjacent gaps then finds the minimum and collects every pair that achieves it.',
    },
    time: ['O(n log n)', 'O(n²)', 'O(n)', 'O(n log² n)'],
    space: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Duplicates give a minimum difference of 0', 'Negative values', 'Exactly two elements'],
    approach: 'Sort the array. One pass computes the minimum gap between neighbours. A second pass (or the same pass, resetting the list when a smaller gap appears) collects every [a[i], a[i+1]] whose gap equals the minimum. The pairs come out already in ascending order.',
  },
  {
    slug: 'first-unique-character-in-a-string', id: 387, title: 'First Unique Character in a String', difficulty: 'Easy', pattern: 'hashing',
    brute: { text: 'For each character, scan the whole string for another copy of it.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'You need the index of the first character that occurs only once.',
      options: [
        'Count every character in one pass, then scan again and return the first index whose count is 1',
        'Keep a set of seen characters and return the index of the first character not yet in the set',
        'Sort the characters and return the index of the first one whose neighbours on both sides are different',
        'Use two pointers from both ends, returning whichever pointer reaches a character that is not repeated',
      ],
      why: 'Uniqueness depends on the whole string, so you count first. A second left-to-right scan then returns the first character with count 1. A "not yet seen" set would just return index 0, and sorting loses the original positions.',
    },
    vars: 'n = length of s (lowercase letters only, so 26 counters)',
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    space: ['O(1)', 'O(n)', 'O(26)', 'O(n²)'],
    edgeCases: ['No unique character: return −1', 'A single character', 'All characters identical'],
    approach: 'Fill a 26-slot count array in one pass over s. Scan s again from the left and return the first index i with count[s[i]] == 1; if none exists return −1.',
  },
  {
    slug: 'first-missing-positive', id: 41, title: 'First Missing Positive', difficulty: 'Hard', pattern: 'hashing', alsoAccept: ['greedy'],
    brute: { text: 'Try 1, 2, 3, … and scan the array for each candidate until one is missing.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(n³)'] },
    insight: {
      q: 'Find the smallest missing positive in O(n) time and O(1) extra space. What is the trick?',
      options: [
        'The answer is in 1..n+1, so use the array as a hash: put each v at index v − 1, then find the first mismatch',
        'Put every value into a HashSet and count upward from 1 until one is missing, which uses only O(1) extra space',
        'Sort the array and return the first gap between neighbouring values, ignoring zero and negative numbers as you go',
        'Return the smallest positive value present plus one, since the missing value must always sit right after that one',
      ],
      why: 'With n numbers the answer cannot exceed n + 1, so only values in 1..n matter. Swapping each such value into its own slot (v at index v − 1) makes the array act as a presence table; the first index i with nums[i] != i + 1 gives the answer i + 1. Each swap places one value for good, so the total is O(n).',
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(n!)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['All values are negative or zero: the answer is 1', '1..n all present: the answer is n + 1', 'Duplicates and values larger than n must be ignored'],
    approach: 'For each i, while nums[i] is in 1..n and nums[nums[i] − 1] != nums[i], swap nums[i] into position nums[i] − 1. Then scan: the first i with nums[i] != i + 1 gives i + 1; if none, return n + 1. Each swap fixes one value, so the loop is O(n).',
  },
  {
    slug: 'rotate-array', id: 189, title: 'Rotate Array', difficulty: 'Medium', pattern: 'two-pointers',
    brute: { text: 'Rotate by one position k times, shifting every element on each rotation.', time: ['O(n·k)', 'O(n)', 'O(n log n)', 'O(k)'] },
    insight: {
      q: 'Rotate right by k in place with O(1) extra space. How?',
      options: [
        'Reverse the whole array, then reverse the first k elements and the remaining n − k separately (with k mod n)',
        'Swap a[i] with a[i + k] for i = 0 to n − k − 1 in a single pass, which moves every element k places to the right',
        'Copy the last k elements into a temporary array, shift the rest by k, and paste the copy back at the front of it',
        'Sort the array by the index (i + k) mod n using a comparator, which places each element in its rotated spot',
      ],
      why: 'Reversing everything puts the last k elements in front but backwards; reversing each of the two blocks restores their internal order. Three reversals touch each element a constant number of times and need no extra array.',
    },
    time: ['O(n)', 'O(n·k)', 'O(n log n)', 'O(k)'],
    space: ['O(1)', 'O(k)', 'O(n)', 'O(log n)'],
    edgeCases: ['k larger than n: use k mod n', 'k = 0 or a multiple of n changes nothing', 'A single-element array'],
    approach: 'Let k = k mod n. Reverse nums[0..n−1], then nums[0..k−1], then nums[k..n−1]. Each reversal is a two-pointer swap loop, so the total is O(n) time and O(1) space.',
  },
  {
    slug: 'reverse-words-in-a-string', id: 151, title: 'Reverse Words in a String', difficulty: 'Medium', pattern: 'two-pointers',
    brute: { text: 'Split on spaces, drop the empty strings, reverse the list and join it with single spaces.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'Reverse the order of the words and collapse the extra spaces. What is the in-place technique?',
      options: [
        'Reverse the whole string, then reverse each word in place, compacting the spaces with a read and a write pointer',
        'Swap the first word with the last, the second with the second to last, and so on in towards the middle of the text',
        'Sort the words alphabetically in descending order and join them back together with single spaces between each pair',
        'Reverse every word on its own and leave the order of the words alone, which reverses the text word by word',
      ],
      why: 'Reversing the whole string puts the words in the right order but spells each one backwards; reversing each word then fixes the spelling. Skipping extra spaces while copying handles the trimming. Words have different lengths, so swapping whole words in place does not work.',
    },
    vars: 'n = length of s (Java strings are immutable, so one char-array copy is needed)',
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(n·w)'],
    space: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    edgeCases: ['Leading and trailing spaces', 'Several spaces between words', 'A single word'],
    approach: 'Copy the string into a char array, reverse it all, then walk it: for each word reverse it in place while writing it to the compacted front, inserting a single space between words. Return the first w characters as a string. O(n) time; the char array is the O(n) space.',
  },
  {
    slug: 'valid-palindrome-ii', id: 680, title: 'Valid Palindrome II', difficulty: 'Easy', pattern: 'two-pointers',
    brute: { text: 'Delete each character in turn and test whether what remains is a palindrome.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'You may delete at most one character. When do you use the deletion?',
      options: [
        'Move two pointers inward; at the first mismatch, try skipping the left or the right character and check the rest',
        'Count the characters with odd frequencies and allow one deletion for each such character that is found in the string',
        'Delete the first mismatching character from the left side only, since the right side is always already correct',
        'Reverse the string and compare it with the original; if more than one position differs, return false at once',
      ],
      why: 'Up to the first mismatch the string is symmetric, so only that mismatch can be repaired, and either the left or the right character must go. Checking both remaining substrings costs O(n) once, so the whole algorithm is linear.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Already a palindrome', 'A mismatch where both skips must be tried', 'Length 1 or 2'],
    approach: 'Two pointers l and r move inward while s[l] == s[r]. On the first mismatch return isPalindrome(l + 1, r) || isPalindrome(l, r − 1), where the helper is a plain two-pointer check. If no mismatch occurs, return true.',
  },
  {
    slug: 'lfu-cache', id: 460, title: 'LFU Cache', difficulty: 'Hard', pattern: 'hashing', alsoAccept: ['linked-list'],
    brute: { text: 'Store a frequency and last-used time with each key and scan every key to find the eviction victim.', time: ['O(c) per operation', 'O(1) per operation', 'O(log c) per operation', 'O(c²) per operation'] },
    insight: {
      q: 'get and put must be O(1), evicting the least frequently used key (the least recently used among ties). What structure?',
      options: [
        'A key-to-node map plus a map from frequency to a doubly linked list of keys, with a running minimum-frequency pointer',
        'A min-heap ordered by (frequency, last-used time), updating the entry for a key every single time that it is used',
        'A single LinkedHashMap in access order, evicting the eldest entry, since that is the least recently used key of all',
        'A sorted array of keys by frequency, using binary search to find a key and shifting entries on each access to it',
      ],
      why: 'Each frequency has its own recency-ordered list, so bumping a key moves its node from the list for f to the list for f + 1 in O(1), and the eviction victim is the tail of the list for the minimum frequency. A heap costs O(log c) per access, and a plain access-ordered map is LRU, which ignores frequency.',
    },
    vars: 'c = capacity',
    time: ['O(1) per operation', 'O(log c) per operation', 'O(c) per operation', 'O(c²) per operation'],
    space: ['O(c)', 'O(1)', 'O(c²)', 'O(log c)'],
    edgeCases: ['Capacity 0: put does nothing', 'Ties in frequency evict the least recently used among them', 'get on a missing key returns −1 and changes nothing'],
    approach: 'Keep keyToNode, freqToList (a LinkedHashSet or doubly linked list per frequency) and minFreq. On get or put of an existing key, remove it from freqToList[f], add it to freqToList[f + 1], and if the old list was the minFreq list and is now empty, increment minFreq. On inserting a new key at capacity, evict the oldest key of freqToList[minFreq], then insert with frequency 1 and set minFreq = 1.',
  },
  {
    slug: 'powx-n', id: 50, title: 'Pow(x, n)', difficulty: 'Medium', pattern: 'bit-manipulation', alsoAccept: ['binary-search'],
    brute: { text: 'Multiply x by itself n times.', time: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'] },
    insight: {
      q: 'For a huge exponent n, how do you avoid doing n multiplications?',
      options: [
        'Square the base and halve the exponent each step, multiplying into the result when the current bit of n is 1',
        'Compute x^(n/2) twice, once for each half, and multiply the two copies together at every level of the recursion',
        'Use Math.exp and Math.log on the base, since library functions run in constant time and are always exact',
        'Cache x^1 to x^n in a table and read the last entry, which is O(1) per query once the table has been built',
      ],
      why: 'x^n = (x²)^(n/2) for even n and x · x^(n−1) for odd n, so the exponent halves every step and only about log₂ n multiplications are needed. Computing the half-power twice brings the cost back to O(n), and a table is itself O(n).',
    },
    time: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'],
    space: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    edgeCases: ['Negative exponents: invert x and negate n', 'n = Integer.MIN_VALUE, whose negation overflows an int (use a long)', 'x = 0, x = 1, or n = 0'],
    approach: 'Convert n to a long; if it is negative set x = 1/x and n = −n. result = 1. While n > 0: if n is odd, result *= x; then x *= x and n >>= 1. Return result. About log₂ n iterations.',
  },
  {
    slug: 'making-a-large-island', id: 827, title: 'Making A Large Island', difficulty: 'Hard', pattern: 'graph-traversal', alsoAccept: ['union-find'],
    brute: { text: 'For every 0 cell, flip it to 1 and flood-fill the whole grid to measure the island it makes.', time: ['O(n⁴)', 'O(n²)', 'O(n² log n)', 'O(n³)'] },
    insight: {
      q: 'You may flip one 0 to 1. How do you find the largest island this can create?',
      options: [
        'Label each island once with its size, then for every 0 add 1 plus the sizes of its distinct neighbouring islands',
        'Flood-fill from each 0 cell separately and count the reachable 1 cells, keeping the largest of those counts',
        'Flip the 0 cell that has the most neighbouring 1s and then run one flood fill from that flipped cell only',
        'Add the sizes of the two largest islands, since flipping a 0 between them always joins them into one',
      ],
      why: 'Labelling once costs O(n²). A flipped 0 joins whichever distinct islands touch it, so its result is 1 plus the sum of those islands\' sizes (counting each id once). Checking every 0 that way is O(1) per cell. Flood-filling per 0 repeats the work n² times.',
    },
    vars: 'n × n = the grid size',
    time: ['O(n²)', 'O(n⁴)', 'O(n³)', 'O(n² log n)'],
    space: ['O(n²)', 'O(1)', 'O(n)', 'O(n³)'],
    edgeCases: ['An all-1 grid: the answer is n²', 'An all-0 grid: flipping one cell gives 1', 'A 0 touching the same island on two sides must not count it twice'],
    approach: 'Flood-fill each island, giving it an id (2, 3, …) and recording sizes[id]. For each 0 cell collect the distinct ids among its four neighbours; its candidate is 1 + the sum of their sizes. The answer is the best candidate, or the biggest island if there is no 0.',
  },
  {
    slug: 'maximum-profit-in-job-scheduling', id: 1235, title: 'Maximum Profit in Job Scheduling', difficulty: 'Hard', pattern: 'dp-1d', alsoAccept: ['binary-search'],
    brute: { text: 'Try every subset of jobs, checking each pair for overlap, and keep the best total profit.', time: ['O(2ⁿ·n)', 'O(n log n)', 'O(n²)', 'O(n)'] },
    insight: {
      q: 'Jobs have start, end and profit, and chosen jobs cannot overlap. What recurrence maximises the profit?',
      options: [
        'Sort by end time; dp[i] = max(dp[i−1], profit[i] + dp[j]) where j is the last job ending at or before job i starts',
        'Sort the jobs by profit and take each one whose interval does not overlap those already chosen, highest first',
        'Sort the jobs by start time and always take the job that starts next, since starting early never loses profit',
        'Sort the jobs by duration and take the shortest ones first, since short jobs leave the most room for the others',
      ],
      why: 'With jobs sorted by end time, the best plan for the first i jobs either skips job i or takes it together with the best plan that ends no later than its start (found by binary search). Greedy orders by profit, start or length all have counterexamples, which is why weighted interval scheduling needs DP.',
    },
    vars: 'n = number of jobs',
    time: ['O(n log n)', 'O(n²)', 'O(n)', 'O(2ⁿ)'],
    space: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Jobs that touch (end = start) are compatible', 'Many jobs with the same end time', 'One job with a huge profit beating many small ones'],
    approach: 'Sort job indices by end time. dp[0] = 0. For job i (1-based in sorted order): find, by binary search over end times, the number j of jobs ending at or before start[i]. dp[i] = max(dp[i−1], dp[j] + profit[i]). Return dp[n].',
  },
  {
    slug: 'restore-ip-addresses', id: 93, title: 'Restore IP Addresses', difficulty: 'Medium', pattern: 'backtracking',
    brute: { text: 'Try every way of inserting three dots into the string and validate each part afterwards.', time: ['O(n³)', 'O(1)', 'O(n)', 'O(2ⁿ)'] },
    insight: {
      q: 'Split the digits into four parts, each 0–255 with no leading zeros. What technique?',
      options: [
        'Backtracking: pick a part of 1 to 3 digits, check it (no leading zero, at most 255), recurse on the rest, then undo it',
        'Dynamic programming over prefixes, since the number of valid splits of a prefix depends only on the shorter prefixes',
        'Greedy: take three digits for each part whenever the value is at most 255, otherwise two digits, and then one',
        'Split the string at every pair of characters using a regular expression and keep the matches that have length four',
      ],
      why: 'There are only four parts of at most three digits each, so the search tree has at most 3⁴ leaves and pruning invalid parts early keeps it tiny. You need all valid splits, not a count or one split, so the choice is made and undone as in any backtracking enumeration.',
    },
    vars: 'n = length of s (at most 20; only strings of 4 to 12 digits can have an answer)',
    time: ['O(1)', 'O(n)', 'O(n²)', 'O(2ⁿ)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Leading zeros: "0" is fine but "01" is not', 'Parts above 255', 'Strings shorter than 4 or longer than 12 digits have no answer'],
    approach: 'dfs(start, parts): if parts == 4 and start == n, record the address. Otherwise for len in 1..3 take s[start..start+len); skip it if it has a leading zero (len > 1) or exceeds 255; append it and recurse with parts + 1; then remove it. Four levels of at most three choices is a bounded search.',
  },
  {
    slug: 'maximal-square', id: 221, title: 'Maximal Square', difficulty: 'Medium', pattern: 'dp-2d',
    brute: { text: 'For every cell as a top-left corner, grow the square while all of its cells are 1.', time: ['O(m·n·min(m, n)²)', 'O(m·n)', 'O(m·n·min(m, n))', 'O(m + n)'] },
    insight: {
      q: 'You want the largest square of 1s. What does dp[i][j] hold?',
      options: [
        'The side of the largest all-1 square ending at (i, j): 1 + min(top, left, top-left) when the cell holds a 1',
        'The number of 1s in the rectangle from the origin to (i, j), computed with a prefix-sum table of the whole grid',
        'The length of the longest run of 1s ending at (i, j) along its row, with the answer being the maximum of those',
        'dp[i−1][j] + dp[i][j−1], counting the paths of 1s that lead to the cell from the top-left corner of the grid',
      ],
      why: 'A square of side k ending at (i, j) needs squares of side k − 1 ending at the cells above, to the left and diagonally up-left, so its side is one more than the smallest of those three. Take the maximum over the table and square it for the area.',
    },
    vars: 'm × n = the size of the grid',
    time: ['O(m·n)', 'O(m·n·min(m, n)²)', 'O(m·n·min(m, n))', 'O(m + n)'],
    space: ['O(m·n)', 'O(1)', 'O(m + n)', 'O(min(m, n)²)'],
    edgeCases: ['No 1s at all: the area is 0', 'The answer is the area (side²), not the side', 'A single row or column: the side is at most 1'],
    approach: 'dp[i][j] = 0 for a 0 cell, else 1 + min(dp[i−1][j], dp[i][j−1], dp[i−1][j−1]) (using 0 outside the grid). Track the maximum side and return side². One row of the table would be enough to cut the space to O(n).',
  },
  {
    slug: 'text-justification', id: 68, title: 'Text Justification', difficulty: 'Hard', pattern: 'greedy',
    brute: { text: 'For each line, try every possible number of words and test whether they fit, rescanning from the start of the line.', time: ['O(n²·W)', 'O(n·W)', 'O(n log n)', 'O(n²)'] },
    insight: {
      q: 'Pack as many words as fit on each line, then distribute the spare spaces. What is the strategy?',
      options: [
        'Greedy: add words while the line fits, spread spaces evenly with extras on the left, left-justify the last line',
        'Dynamic programming over the word breaks that minimises the total squared leftover space across all of the lines',
        'Place the longest words first on each line and fill the remaining space with the shortest words that are left over',
        'Cut the text into lines of exactly maxWidth characters and then move any broken word down to the next line',
      ],
      why: 'The problem fixes the layout rule: take as many words as fit. So packing is greedy, and each line is then formatted independently with the spaces split as evenly as possible. The last line and single-word lines are left-justified instead. Minimising raggedness is a different (DP) problem.',
    },
    vars: 'n = number of words, W = maxWidth',
    time: ['O(n·W)', 'O(n²·W)', 'O(n log n)', 'O(n²)'],
    space: ['O(n·W)', 'O(1)', 'O(n)', 'O(W)'],
    edgeCases: ['A line with a single word is left-justified', 'The last line is left-justified with single spaces', 'Extra spaces go to the leftmost gaps'],
    approach: 'Walk the words keeping the current line\'s words and their total letter length. When adding the next word (plus one space per gap) would exceed W, justify the line: gaps = words − 1; if one word or it is the last line, left-justify and pad with spaces; otherwise each gap gets (W − letters) / gaps spaces and the first (W − letters) % gaps gaps get one extra. Then start a new line.',
  },
  {
    slug: 'burst-balloons', id: 312, title: 'Burst Balloons', difficulty: 'Hard', pattern: 'dp-2d',
    brute: { text: 'Try every order of bursting the balloons recursively.', time: ['O(n!)', 'O(n³)', 'O(n²)', 'O(2ⁿ)'] },
    insight: {
      q: 'Bursting a balloon changes its neighbours. What subproblem makes the pieces independent?',
      options: [
        'Interval DP on the LAST balloon burst in (i, j): max over k of dp[i][k] + dp[k][j] + nums[i]·nums[k]·nums[j]',
        'Interval DP on the FIRST balloon to burst in (i, j), since its neighbours at that moment are just its original ones',
        'Greedy: always burst the balloon with the smallest value next, since it costs the least to remove at each step taken',
        'dp[i] = the best coins using the first i balloons, taking the best last burst position found in that prefix',
      ],
      why: 'If balloon k is the last one burst between i and j, its neighbours at that moment are exactly i and j, and the two sides (i, k) and (k, j) were popped independently before it. Choosing the first balloon instead leaves neighbours that depend on later bursts, so the pieces are not independent.',
    },
    vars: 'n = number of balloons',
    time: ['O(n³)', 'O(n²)', 'O(n!)', 'O(n² log n)'],
    space: ['O(n²)', 'O(n)', 'O(1)', 'O(n³)'],
    edgeCases: ['Pad the array with a virtual 1 at each end', 'A single balloon', 'Zeros inside the array'],
    approach: 'Pad nums with 1 on both sides. For interval length 2 up to n + 1, for each i with j = i + len: dp[i][j] = max over k in (i, j) of dp[i][k] + dp[k][j] + nums[i]·nums[k]·nums[j]. Return dp[0][n + 1].',
  },
  {
    slug: 'search-suggestions-system', id: 1268, title: 'Search Suggestions System', difficulty: 'Medium', pattern: 'trie', alsoAccept: ['binary-search'],
    brute: { text: 'For each typed prefix, scan every product and collect the three smallest matches.', time: ['O(L·n·m)', 'O(n·m·log n + L·m·log n)', 'O(L·m)', 'O(n)'] },
    insight: {
      q: 'After each typed letter, return up to three lexicographically smallest products with that prefix. What do you do?',
      options: [
        'Sort the products, then binary-search the first product ≥ each prefix and take up to three that share that prefix',
        'Hash every product by its first letter and return the first three entries of that bucket for every typed prefix',
        'Rescan all of the products for every prefix and keep the three longest matches, since longer ones are more relevant',
        'Keep a max-heap of all the products and pop the top three after every letter that is typed into the search word',
      ],
      why: 'In sorted order, all products with a given prefix are contiguous, so one binary search finds the start and the next three entries are the answer if they share the prefix. A trie that stores the first three words on each node does the same job.',
    },
    vars: 'n = products, m = longest product length, L = length of the search word',
    time: ['O(n·m·log n + L·m·log n)', 'O(L·n·m)', 'O(n + L)', 'O(n²·m)'],
    space: ['O(n·m)', 'O(1)', 'O(L)', 'O(n²)'],
    edgeCases: ['Fewer than three matches', 'No matches for later prefixes (empty lists)', 'Duplicate products'],
    approach: 'Sort products. For each prefix of searchWord, binary-search the lowest index lo with products[lo] ≥ prefix; then collect up to three products from lo onward that start with the prefix. Because the list is sorted, lo only moves forward as the prefix grows.',
  },
  {
    slug: 'wildcard-matching', id: 44, title: 'Wildcard Matching', difficulty: 'Hard', pattern: 'dp-2d', alsoAccept: ['greedy'],
    brute: { text: 'Recursively try every way a * can match zero or more characters, with no memo.', time: ['O(2^(n+m))', 'O(n·m)', 'O(n + m)', 'O(n²)'] },
    insight: {
      q: '? matches any one character and * matches any sequence. What state do you track?',
      options: [
        'dp[i][j] = does s[0..i) match p[0..j); a * takes dp[i][j−1] or dp[i−1][j], while ? and letters take dp[i−1][j−1]',
        'Convert the pattern to a regular expression and call the library matcher once, which always runs in linear time',
        'Greedy left-to-right: every * swallows as many characters as possible and never gives any of them back again',
        'Compare the two strings from both ends inward and treat the middle as matched whenever a * is present in it',
      ],
      why: 'A * can absorb nothing (look at the pattern without it) or one more character of the string (look at the string without that character, same pattern), and ? or a literal consumes one of each. That gives a table of (prefix, prefix) states, each computed once.',
    },
    vars: 'n = length of s, m = length of p',
    time: ['O(n·m)', 'O(2^(n+m))', 'O(n + m)', 'O(n²)'],
    space: ['O(n·m)', 'O(1)', 'O(n + m)', 'O(m)'],
    edgeCases: ['An empty string against a pattern made only of *', 'Consecutive * characters', 'A pattern longer than the string'],
    approach: 'dp[0][0] = true, and dp[0][j] = dp[0][j−1] while p[j−1] is *. For i ≥ 1, j ≥ 1: if p[j−1] is *, dp[i][j] = dp[i][j−1] || dp[i−1][j]; else if p[j−1] is ? or equals s[i−1], dp[i][j] = dp[i−1][j−1]. Return dp[n][m].',
  },
  {
    slug: 'bus-routes', id: 815, title: 'Bus Routes', difficulty: 'Hard', pattern: 'graph-traversal',
    brute: { text: 'BFS over stops, finding each stop\'s neighbours by scanning every route.', time: ['O(S·R)', 'O(S)', 'O(R log R)', 'O(R²)'] },
    insight: {
      q: 'You want the fewest buses from source to target. What should the BFS count as one step?',
      options: [
        'Boarding a bus: map each stop to its routes, and enqueue the unvisited routes reachable from the stops you reach',
        'Travelling one stop, adding 1 to the count every time the traveller moves on from one stop to the next stop',
        'Dijkstra over stops using the number of stops between them as the edge weight, then dividing by the route length',
        'Union-find over the stops; the answer is the number of unions that are needed to connect the source to the target',
      ],
      why: 'Riding along a route is free, and only boarding costs 1, so the graph that matters has routes as nodes (two routes are adjacent if they share a stop). BFS over routes, using a stop-to-routes map, gives the fewest buses and visits each route once.',
    },
    vars: 'S = total stops across all routes, R = number of routes',
    time: ['O(S)', 'O(S·R)', 'O(R²)', 'O(S log R)'],
    space: ['O(S)', 'O(1)', 'O(R)', 'O(S·R)'],
    edgeCases: ['source equals target: 0 buses', 'The target is unreachable: −1', 'A stop served by many routes'],
    approach: 'If source == target return 0. Build stopToRoutes. BFS from the routes at the source with a visited set of routes and of stops; each layer is one more bus. When a route containing target is dequeued return its layer count; if the queue empties return −1.',
  },
  {
    slug: 'find-k-closest-elements', id: 658, title: 'Find K Closest Elements', difficulty: 'Medium', pattern: 'binary-search', alsoAccept: ['two-pointers'],
    brute: { text: 'Sort all elements by (distance to x, value), take the first k, then sort them back by value.', time: ['O(n log n)', 'O(log n + k)', 'O(n)', 'O(k log n)'] },
    insight: {
      q: 'The array is sorted. How do you find the k closest elements to x quickly?',
      options: [
        'Binary-search the left end of the k-window: compare x − arr[mid] with arr[mid + k] − x to decide which way to move',
        'Binary-search for x and return the k elements immediately to its right, since larger values are always closer to it',
        'Keep a max-heap of size k keyed on distance and scan the whole array once, which is optimal for sorted input data',
        'Take the first k elements if x is below the median of the array, and the last k elements otherwise',
      ],
      why: 'The answer is always k consecutive elements, so you only need to find where that window starts. If arr[mid] is farther from x than arr[mid + k], the window must start to the right of mid; otherwise it can start at mid or to its left. That is a binary search over window starts.',
    },
    vars: 'n = length of arr, k = elements to return',
    time: ['O(log(n − k) + k)', 'O(n log n)', 'O(n)', 'O(k log n)'],
    space: ['O(k)', 'O(1)', 'O(n)', 'O(log n)'],
    edgeCases: ['x below every element or above every element', 'Ties in distance prefer the smaller value', 'k equals the array length'],
    approach: 'Search lo = 0, hi = n − k. While lo < hi: mid = (lo + hi) / 2; if x − arr[mid] > arr[mid + k] − x then lo = mid + 1 else hi = mid. Return arr[lo .. lo + k − 1]. The binary search is over window starts, then k elements are copied out.',
  },
  {
    slug: 'best-time-to-buy-and-sell-stock-ii', id: 122, title: 'Best Time to Buy and Sell Stock II', difficulty: 'Medium', pattern: 'greedy', alsoAccept: ['dp-1d'],
    brute: { text: 'Recursively try buying or selling on every day with no memo.', time: ['O(2ⁿ)', 'O(n)', 'O(n²)', 'O(n log n)'] },
    insight: {
      q: 'You may buy and sell many times (holding one share at a time). What is the optimal strategy?',
      options: [
        'Add every positive day-to-day price difference: each rise can be captured as its own buy-and-sell pair',
        'Buy at the global minimum price and sell at the global maximum price that appears after it in the array',
        'Sell on every peak and buy on every valley, but skip any peak that is lower than the previous peak',
        'Sort the prices and take the difference between the largest and smallest value as the best total profit',
      ],
      why: 'A rise from a to c through b equals the rise a→b plus b→c, so any profitable stretch is the sum of its daily gains. Taking every positive daily difference captures all of them and ignores the falls, which is exactly the maximum.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Prices only fall: the profit is 0', 'A single day', 'Equal consecutive prices (no trade)'],
    approach: 'profit = 0. For i from 1: if prices[i] > prices[i − 1] add the difference to profit. Return profit.',
  },
  {
    slug: 'delete-and-earn', id: 740, title: 'Delete and Earn', difficulty: 'Medium', pattern: 'dp-1d',
    brute: { text: 'Try deleting each value in every order and recurse on what remains.', time: ['O(2ⁿ)', 'O(n + M)', 'O(n²)', 'O(n log n)'] },
    insight: {
      q: 'Taking value v deletes every v − 1 and v + 1. How do you reduce it to a known DP?',
      options: [
        'Total the points of each value into an array indexed by value; then it is House Robber over adjacent values',
        'Sort the values and take every second element of the sorted array, since adjacent values cannot both be chosen',
        'Greedily take the value with the largest total points, delete its neighbours, and repeat on whatever is left over',
        'Use a sliding window of width 3 over the sorted values and take the largest total that is inside each window',
      ],
      why: 'Taking any one copy of v lets you take all the copies for free, so each value is worth count × v. Choosing a value forbids v ± 1, which is exactly the "no two adjacent houses" constraint over the number line of values. Greedy picks by largest total can block better pairs.',
    },
    vars: 'n = number of values, M = the largest value',
    time: ['O(n + M)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(M)', 'O(1)', 'O(n)', 'O(n²)'],
    edgeCases: ['Many copies of one value add up', 'Gaps between values (no neighbours to lose)', 'A single value'],
    approach: 'points[v] = v × (count of v). Then take = points[0], skip = 0; for v from 1 to M: newTake = skip + points[v]; skip = max(skip, take); take = newTake. Return max(take, skip). This is House Robber over the values.',
  },
];
