import type { CuratedProblem } from '../types.ts';

// Second pass over each pattern: two more problems apiece. First option is the correct one.

export const extraArrayProblems: CuratedProblem[] = [
  {
    slug: 'isomorphic-strings', id: 205, title: 'Isomorphic Strings', difficulty: 'Easy', pattern: 'hashing',
    brute: { text: 'For every pair of positions, check the two letters agree in both strings.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(2ⁿ)'] },
    insight: {
      q: 'What exactly makes two strings isomorphic?',
      options: [
        'A one-to-one mapping in BOTH directions, so check s → t and t → s',
        'Every character of s appears somewhere in t, in any position',
        'The two strings contain the same set of distinct characters',
        'A single map from s to t, since the lengths already match',
      ],
      why: 'The mapping must be a bijection. "badc" → "baba" satisfies s → t on its own but sends two letters to one, so the reverse map (or comparing each character\'s first-occurrence index) is what rejects it.',
    },
    vars: 'n = length of the strings; the character set is fixed',
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Different lengths (false)', 'A letter mapping to itself', 'Two letters mapping to one ("badc" vs "baba")'],
    approach:
      "Keep two arrays of last-seen positions (or two maps). At each index the previous position of s[i] must equal that of t[i]; otherwise return false. Comparing the two strings' first-occurrence patterns is the same check.",
  },
  {
    slug: '4sum-ii', id: 454, title: '4Sum II', difficulty: 'Medium', pattern: 'hashing',
    brute: { text: 'Four nested loops over the four arrays.', time: ['O(n⁴)', 'O(n³)', 'O(n²)', 'O(n log n)'] },
    insight: {
      q: 'How do you count the quadruples without trying all n⁴?',
      options: [
        'Count every a + b in a map, then look up −(c + d) for the other two arrays',
        'Sort all four arrays and sweep them with two pointers',
        'Fix each value of the first array and run 3Sum on the other three',
        'Add up all four arrays and check which totals are zero',
      ],
      why: 'Splitting 4 arrays into 2 + 2 turns O(n⁴) into two O(n²) passes: the map holds each a + b sum with how often it occurred, and every c + d looks up its complement. Counts matter, since sums repeat.',
    },
    vars: 'n = length of each array',
    time: ['O(n²)', 'O(n³)', 'O(n⁴)', 'O(n log n)'],
    space: ['O(n²)', 'O(n)', 'O(1)', 'O(n³)'],
    edgeCases: ['All zeros (n⁴ quadruples)', 'Negative numbers', 'Repeated sums must accumulate, not overwrite'],
    approach: 'Build map[a + b] += 1 over A × B. Then for each c in C and d in D add map.getOrDefault(−(c + d), 0).',
  },
  {
    slug: 'squares-of-a-sorted-array', id: 977, title: 'Squares of a Sorted Array', difficulty: 'Easy', pattern: 'two-pointers',
    brute: { text: 'Square every value, then sort the result.', time: ['O(n log n)', 'O(n)', 'O(n²)', 'O(log n)'] },
    insight: {
      q: 'The input is sorted but has negatives. How do you get sorted squares in O(n)?',
      options: [
        'Compare the two ends and fill the result from the back with the larger square',
        'Square every value and sort the result afterwards',
        'Square every value; squaring keeps the order the input already had',
        'Push all the squares into a max-heap and pop them into the result',
      ],
      why: 'The biggest square sits at one end or the other, so filling the answer from the back is a single pass. Sorting costs O(n log n), and squaring alone breaks the order as soon as a negative is present.',
    },
    vars: "n = length of nums; the returned array doesn't count as extra space",
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    space: ['O(1)', 'O(n)', 'O(n log n)', 'O(n²)'],
    edgeCases: ['All negative numbers', 'All non-negative numbers', 'A single element'],
    approach: 'i = 0, j = n − 1, write at position n − 1 downwards: compare nums[i]² with nums[j]², write the larger, move that pointer inward.',
  },
  {
    slug: 'boats-to-save-people', id: 881, title: 'Boats to Save People', difficulty: 'Medium', pattern: 'two-pointers',
    alsoAccept: ['greedy'],
    brute: { text: 'Try every way of pairing people up and keep the best.', time: ['O(2ⁿ)', 'O(n²)', 'O(n log n)', 'O(n)'] },
    insight: {
      q: 'Each boat takes at most two people within the limit. How do you use the fewest?',
      options: [
        'Sort, then pair the lightest with the heaviest when they fit',
        'Sort and pair neighbours starting from the heaviest end',
        'Give everyone above half the limit their own boat, then pair the rest',
        'Fill each boat with the two lightest people remaining',
      ],
      why: 'The heaviest person has to sail now, and taking the lightest along costs nothing: if they fit, no pairing is better; if they do not, that person is alone in any plan. That is a textbook exchange argument.',
    },
    time: ['O(n log n)', 'O(n)', 'O(n²)', 'O(n log limit)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Everyone above half the limit', 'Two people exactly at the limit', 'A single person'],
    approach: 'Sort. lo = 0, hi = n − 1, boats = 0. While lo <= hi: if people[lo] + people[hi] <= limit, lo++. Always hi-- and boats++.',
  },
  {
    slug: 'max-consecutive-ones-iii', id: 1004, title: 'Max Consecutive Ones III', difficulty: 'Medium', pattern: 'sliding-window',
    brute: { text: 'From every start, extend while the zeros used stay within k.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(2ⁿ)'] },
    insight: {
      q: 'You may flip at most k zeros. When is a window valid?',
      options: [
        'While it holds at most k zeros',
        'While it holds at least k ones, whatever the length',
        'While it holds no more than k ones in total',
        'While the zeros inside it sit next to each other',
      ],
      why: 'Flipping is only limited by how many zeros the window contains, so grow right and, whenever the zero count passes k, move left past one zero. The largest window seen is the answer.',
    },
    time: ['O(n)', 'O(n · k)', 'O(n log n)', 'O(n²)'],
    space: ['O(1)', 'O(k)', 'O(n)', 'O(n²)'],
    edgeCases: ['k = 0', 'k at least the number of zeros (whole array)', 'No zeros at all'],
    approach: 'left = 0, zeros = 0. For each right: zeros += (nums[right] == 0). While zeros > k: zeros -= (nums[left++] == 0). Track right − left + 1.',
  },
  {
    slug: 'find-all-anagrams-in-a-string', id: 438, title: 'Find All Anagrams in a String', difficulty: 'Medium', pattern: 'sliding-window',
    brute: { text: 'Sort each window of length |p| and compare it with sorted p.', time: ['O(n · m log m)', 'O(n · m)', 'O(n)', 'O(n!)'] },
    insight: {
      q: 'How do you find every start index whose window is an anagram of p?',
      options: [
        'Slide a window of length |p|, updating letter counts by one in and one out',
        'Sort p, then sort each window of that length and compare them',
        'Check that every letter of p occurs in the window, ignoring counts',
        'Search the string for each permutation of p in turn',
      ],
      why: 'An anagram has the same letter counts and the same length, so only the entering and leaving letters change per step. Comparing 26 counts (or keeping a "how many letters match" counter) makes each position O(1).',
    },
    vars: 'n = length of s, m = length of p',
    time: ['O(n)', 'O(n · m log m)', 'O(n · m)', 'O(m!)'],
    space: ['O(1)', 'O(n)', 'O(m)', 'O(n · m)'],
    edgeCases: ['p longer than s (no answers)', 'Repeated letters in p', 'Overlapping answers ("abab" with p = "ab")'],
    approach: 'Count p into need[26]. Slide a window of length m over s keeping have[26]; every time the two agree, record the window\'s left index.',
  },
  {
    slug: 'continuous-subarray-sum', id: 523, title: 'Continuous Subarray Sum', difficulty: 'Medium', pattern: 'prefix-sum',
    brute: { text: 'Test every subarray of length at least 2 for divisibility.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(n · k)'] },
    insight: {
      q: 'You need a subarray of length ≥ 2 whose sum is a multiple of k. What do you store?',
      options: [
        'The FIRST index at which each prefix remainder appeared',
        'Every prefix sum, looking for two that are equal',
        'A running sum that resets whenever it passes k',
        'How many times each remainder has occurred so far',
      ],
      why: 'sum(i..j) is a multiple of k exactly when prefix[i] and prefix[j] leave the same remainder. Keeping the first index of each remainder maximizes the gap, which is what the "at least two elements" rule needs. Seed the map with {0: −1}.',
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(n · k)'],
    space: ['O(min(n, k))', 'O(1)', 'O(n²)', 'O(k²)'],
    edgeCases: ['[0, 0] is valid for any k', 'k larger than every sum', 'Negative numbers: normalize with ((r % k) + k) % k'],
    approach: 'Walk with a running sum; r = ((sum % k) + k) % k. If r was seen at index i and now − i >= 2 return true; otherwise store the first index of r. Seed {0: −1}.',
  },
  {
    slug: 'subarray-sums-divisible-by-k', id: 974, title: 'Subarray Sums Divisible by K', difficulty: 'Medium', pattern: 'prefix-sum',
    brute: { text: 'Sum every subarray and test it modulo k.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(n · k)'] },
    insight: {
      q: 'How do you count every subarray whose sum divides by k?',
      options: [
        'Count prefixes per remainder and add how many earlier prefixes share it',
        'Count the prefix sums that are themselves multiples of k',
        'Slide a window that shrinks whenever its sum passes k',
        'Store the first index of each remainder and subtract indices',
      ],
      why: 'Two prefixes with the same remainder bound a subarray divisible by k, so every pair of equal remainders is one answer. Java\'s % can return a negative, so normalize with ((r % k) + k) % k, and seed remainder 0 with the empty prefix.',
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(n · k)'],
    space: ['O(k)', 'O(1)', 'O(n)', 'O(n · k)'],
    edgeCases: ['Negative numbers', 'k = 1 (every subarray counts)', 'Single-element subarrays'],
    approach: 'counts[0] = 1. For each x: sum += x; r = ((sum % k) + k) % k; total += counts[r]; counts[r]++.',
  },
  {
    slug: 'search-insert-position', id: 35, title: 'Search Insert Position', difficulty: 'Easy', pattern: 'binary-search',
    brute: { text: 'Walk the array until a value is not smaller than the target.', time: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'What are you really searching for when the target is missing?',
      options: [
        'The first index whose value is ≥ target, which is where it belongs',
        'The closest value, then one past it when that value is smaller',
        'The middle of the range where the search happened to stop',
        'The last index whose value is ≤ target',
      ],
      why: 'The insert position is the count of elements strictly below the target, i.e. the lower bound. The loop while (lo < hi) with hi = mid or lo = mid + 1 lands on it, and returns n when every element is smaller.',
    },
    time: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'],
    space: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    edgeCases: ['Target below everything (0)', 'Target above everything (n)', 'Target already present'],
    approach: 'lo = 0, hi = n. While lo < hi: mid = lo + (hi − lo) / 2; if nums[mid] < target lo = mid + 1 else hi = mid. Return lo.',
  },
  {
    slug: 'capacity-to-ship-packages-within-d-days', id: 1011, title: 'Capacity To Ship Packages Within D Days', difficulty: 'Medium', pattern: 'binary-search',
    brute: { text: 'Try every capacity from the heaviest package upward.', time: ['O(n · S)', 'O(n log S)', 'O(n)', 'O(S log n)'] },
    insight: {
      q: 'What do you binary-search over, and what is the test?',
      options: [
        'The capacity, from max(weight) up to the total weight',
        'Capacity from 1 upward, trying every value until one works',
        'The number of days, from 1 to d, checking each in turn',
        'The split points between days, chosen by dynamic programming',
      ],
      why: 'Days needed never increases as capacity grows, so "fits within d days" flips exactly once. The capacity can never be below the heaviest package, and never needs to exceed the total weight.',
    },
    vars: 'n = number of packages, S = total weight',
    time: ['O(n log S)', 'O(n · S)', 'O(n log n)', 'O(S log n)'],
    space: ['O(1)', 'O(n)', 'O(S)', 'O(log S)'],
    edgeCases: ['d equals n (answer = heaviest package)', 'd = 1 (answer = total weight)', 'One unusually heavy package'],
    approach: 'lo = max(weights), hi = sum(weights). While lo < hi: mid; simulate filling days greedily; if days <= d hi = mid else lo = mid + 1. Return lo.',
  },
];

export const extraStackListProblems: CuratedProblem[] = [
  {
    slug: 'simplify-path', id: 71, title: 'Simplify Path', difficulty: 'Medium', pattern: 'stack',
    brute: { text: 'Rescan the whole path for a "name/.." pair after each removal.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(2ⁿ)'] },
    insight: {
      q: 'How do you resolve "." and ".." in a Unix path?',
      options: [
        'Split on "/" and push names on a stack; ".." pops, "." and empties are skipped',
        'Repeatedly replace "name/.." with nothing until the string stops changing',
        'Count the ".." segments and drop that many names from the end',
        'Delete every "." and ".." and join whatever is left',
      ],
      why: 'A stack mirrors the directory chain: ".." steps out (pop when there is something to pop), "." stays put, and repeated slashes are empty pieces. Counting ".." fails because a pop at the root does nothing.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    space: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    edgeCases: ['".." at the root changes nothing', 'A trailing slash is dropped', '"..." is an ordinary directory name'],
    approach: 'For each piece of path.split("/"): skip "" and "."; pop on ".." when non-empty; otherwise push. Return "/" + String.join("/", stack), or "/" when empty.',
  },
  {
    slug: 'basic-calculator-ii', id: 227, title: 'Basic Calculator II', difficulty: 'Medium', pattern: 'stack',
    brute: { text: 'Scan repeatedly, folding one × or ÷ per pass, then add up what is left.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(2ⁿ)'] },
    insight: {
      q: 'How do you honour × and ÷ precedence without building a parse tree?',
      options: [
        'Stack the additive terms; combine × and ÷ immediately',
        'Evaluate strictly left to right, then multiply at the end',
        'Apply each operator the moment you read it in the string',
        'Split the expression into equal parts by operator count',
      ],
      why: 'Only + and − wait, so the stack holds terms whose sum is the answer. When the pending operator is × or ÷, the left operand is already on top of the stack and can be combined at once.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    edgeCases: ['Spaces anywhere in the string', 'Division truncates toward zero', 'Multi-digit numbers'],
    approach: 'Track num and the previous operator (start with +). At each operator or at the end: + pushes num, − pushes −num, × pushes pop() * num, ÷ pushes pop() / num. Sum the stack.',
  },
  {
    slug: 'sum-of-subarray-minimums', id: 907, title: 'Sum of Subarray Minimums', difficulty: 'Medium', pattern: 'monotonic-stack',
    brute: { text: 'Walk every subarray keeping its running minimum.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(n³)'] },
    insight: {
      q: 'How do you total the minimum of every subarray without listing them?',
      options: [
        'Count the subarrays each element dominates, then weight it',
        'Sort the array and weight each value by its position',
        'Slide a window over the array and take its minimum each step',
        'Sum the array and divide by the number of subarrays',
      ],
      why: 'An element is the minimum of exactly the subarrays that reach neither smaller neighbour, so its contribution is value × left span × right span. A monotonic stack finds both boundaries in O(n); make one side strict so equal values are not counted twice.',
    },
    vars: 'n = length of arr; the answer is taken modulo 1e9+7',
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(n³)'],
    space: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    edgeCases: ['Equal values (count each subarray once)', 'A strictly increasing array', 'Keep the running total in a long'],
    approach: 'With an increasing stack find prevSmaller and nextSmaller for every index, then add arr[i] × (i − prev) × (next − i), modulo 1e9+7.',
  },
  {
    slug: 'next-greater-element-ii', id: 503, title: 'Next Greater Element II', difficulty: 'Medium', pattern: 'monotonic-stack',
    brute: { text: 'From each index, walk around the circle until a bigger value shows up.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(n³)'] },
    insight: {
      q: 'The array is circular. How do you handle the wrap-around?',
      options: [
        'Walk 2n indices using i % n, with the usual decreasing stack',
        'Run the normal scan, then give every unanswered index the array maximum',
        'Sort the array and answer each value with its successor',
        'Reverse the array, scan again, and merge the two answers',
      ],
      why: 'Two laps let every element see the whole array, including what wraps around; indices taken modulo n keep the bookkeeping simple. Only the first lap pushes indices, because anything popped later already has its answer.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    edgeCases: ['All values equal (every answer −1)', 'A strictly decreasing array (answers wrap)', 'A single element'],
    approach: 'Fill the answer with −1. For i in 0..2n−1: while the stack is non-empty and nums[i % n] > nums[top], pop and answer it; push i only while i < n.',
  },
  {
    slug: 'add-two-numbers', id: 2, title: 'Add Two Numbers', difficulty: 'Medium', pattern: 'linked-list',
    brute: { text: 'Copy both lists into arrays, add them there, and rebuild.', time: ['O(m + n)', 'O(m · n)', 'O((m + n) log(m + n))', 'O((m + n)²)'] },
    insight: {
      q: 'The digits are stored in reverse order. What does the loop need?',
      options: [
        'A carry: append (sum % 10) and keep (sum / 10) for the next node',
        'To convert both lists to integers, add them, and rebuild a list',
        'To reverse both lists first, then add from the heads',
        'To pad the shorter list with zeros and add digit by digit',
      ],
      why: 'Reverse order means the heads are the least significant digits, so ordinary addition runs front to back with a carry. Converting to a number overflows long before the 100-digit limit, and a leftover carry needs one more node.',
    },
    vars: "m, n = lengths of the lists; the returned list doesn't count as extra space",
    time: ['O(m + n)', 'O(m · n)', 'O(max(m, n) log n)', 'O((m + n)²)'],
    space: ['O(1)', 'O(m + n)', 'O(max(m, n))', 'O(m · n)'],
    edgeCases: ['Different lengths', 'A final carry ([9,9] + [1])', 'Single-digit lists'],
    approach: 'Dummy head; while either list remains or carry != 0: sum = carry + a.val + b.val (0 for a missing node); append new ListNode(sum % 10); carry = sum / 10.',
  },
  {
    slug: 'swap-nodes-in-pairs', id: 24, title: 'Swap Nodes in Pairs', difficulty: 'Medium', pattern: 'linked-list',
    brute: { text: 'Copy the values into an array, swap them in pairs, write them back.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'How do you swap each pair without touching the values?',
      options: [
        'Rewire prev → second → first → rest, then move prev on by two nodes',
        'Swap the val fields of each pair, which is simpler and equivalent',
        'Reverse the whole list and then swap the two halves',
        'Copy the nodes into an array, swap there, and relink',
      ],
      why: 'Each swap rewires three links, and a dummy node makes the first pair behave like every other. The problem explicitly forbids changing node values, which rules out the val-swap shortcut.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['Odd length (the last node stays put)', 'Empty list', 'Exactly two nodes'],
    approach: 'dummy.next = head; prev = dummy. While prev.next and prev.next.next: first = prev.next; second = first.next; first.next = second.next; second.next = first; prev.next = second; prev = first.',
  },
  {
    slug: 'palindrome-linked-list', id: 234, title: 'Palindrome Linked List', difficulty: 'Easy', pattern: 'fast-slow',
    alsoAccept: ['linked-list'],
    brute: { text: 'Copy the values into a list and compare it with its reverse.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'How do you check it with O(1) extra space?',
      options: [
        'Find the middle with slow/fast, reverse the second half, compare the halves',
        'Push every value on a stack, then walk the list again comparing pops',
        'Compare the first and last nodes and move both inward',
        'Count the nodes, then compare node i with node n − 1 − i',
      ],
      why: 'Reversing the back half lets one forward walk compare mirrored values with no extra memory. A stack or array copy costs O(n), and a singly linked list cannot be walked backwards.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['Odd length (the middle node is skipped)', 'Two nodes', 'Restoring the list afterwards is polite'],
    approach: 'slow/fast to the middle; reverse from slow; walk one pointer from head and one from the reversed head comparing values until either ends.',
  },
  {
    slug: 'circular-array-loop', id: 457, title: 'Circular Array Loop', difficulty: 'Medium', pattern: 'fast-slow',
    brute: { text: 'From each start, follow up to n steps recording the path in a set.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(2ⁿ)'] },
    insight: {
      q: 'What counts as a valid cycle here?',
      options: [
        'One longer than a single element whose moves all go the same way',
        'Any index you can return to after some number of moves',
        'A cycle that visits every index of the array',
        'Only cycles made of forward moves',
      ],
      why: 'A one-element self-loop and a loop mixing forward and backward moves are both invalid. Running slow/fast from each start while checking the sign of every step rejects them; zeroing out dead paths keeps the whole scan linear.',
    },
    time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    edgeCases: ['A single-element loop is invalid', 'Direction changes inside a loop', 'Indices wrap: ((i + nums[i]) % n + n) % n'],
    approach: 'For each start run slow/fast over next(i) = ((i + nums[i]) % n + n) % n, aborting if the sign flips or next(i) == i. If they meet, return true; otherwise set the visited path to 0.',
  },
];

export const extraTreeHeapProblems: CuratedProblem[] = [
  {
    slug: 'subtree-of-another-tree', id: 572, title: 'Subtree of Another Tree', difficulty: 'Easy', pattern: 'tree-dfs',
    brute: { text: 'Compare subRoot with the subtree rooted at each node.', time: ['O(n · m)', 'O(n + m)', 'O(n²)', 'O(n log m)'] },
    insight: {
      q: 'How do you test whether subRoot appears somewhere in root?',
      options: [
        'At every node, run a "same tree" check against subRoot',
        'Compare the in-order traversals of the two trees as strings',
        'Check that every value in subRoot also occurs in root',
        'Compare the heights first, then the root values',
      ],
      why: 'Being a subtree means some node is the root of an identical tree, so the test is sameTree at each candidate node. Serializing works too, but only with null markers: a bare traversal matches across different shapes.',
    },
    vars: 'n = nodes in root, m = nodes in subRoot',
    time: ['O(n · m)', 'O(n + m)', 'O(n log m)', 'O(n²)'],
    space: ['O(height of root)', 'O(n · m)', 'O(n + m)', 'O(1)'],
    edgeCases: ['subRoot is a single node', 'Same values arranged differently', 'subRoot equal to the whole tree'],
    approach: 'isSubtree(node) = node != null && (sameTree(node, subRoot) || isSubtree(node.left) || isSubtree(node.right)); sameTree compares values and both children.',
  },
  {
    slug: 'path-sum-ii', id: 113, title: 'Path Sum II', difficulty: 'Medium', pattern: 'tree-dfs',
    alsoAccept: ['backtracking'],
    brute: { text: 'Enumerate every downward path, not just the root-to-leaf ones.', time: ['O(n²)', 'O(n · h)', 'O(n)', 'O(2ⁿ)'] },
    insight: {
      q: 'How do you collect every root-to-leaf path with the target sum?',
      options: [
        'DFS with the remaining sum; record a copy at a matching leaf',
        'Sum every subtree and keep the ones that match the target',
        'Record the path whenever the running sum matches, leaf or not',
        'Find one matching path, subtract it, and repeat from there',
      ],
      why: 'Only complete root-to-leaf paths count, so the check belongs at a node with two null children. Store a copy of the path — the same list keeps changing — and remove the last node when backtracking.',
    },
    vars: 'n = number of nodes, h = height',
    time: ['O(n · h)', 'O(n)', 'O(n²)', 'O(2ⁿ)'],
    space: ['O(h)', 'O(n)', 'O(n · h)', 'O(1)'],
    edgeCases: ['Negative values (you cannot stop early)', 'The sum matching at an internal node', 'Empty tree'],
    approach: 'dfs(node, remaining, path): append node; if it is a leaf and remaining == node.val record a copy; else recurse both children with remaining − node.val; remove the last element.',
  },
  {
    slug: 'minimum-depth-of-binary-tree', id: 111, title: 'Minimum Depth of Binary Tree', difficulty: 'Easy', pattern: 'tree-bfs',
    alsoAccept: ['tree-dfs'],
    brute: { text: 'Explore every root-to-leaf path and keep the shortest.', time: ['O(n)', 'O(n²)', 'O(2ⁿ)', 'O(n log n)'] },
    insight: {
      q: 'Why does BFS suit this better than DFS?',
      options: [
        'It reaches the shallowest leaf first and can stop there',
        'DFS cannot compute depths on a binary tree at all',
        'BFS always visits fewer nodes than DFS does in a tree',
        'Only BFS can tell a leaf apart from an internal node',
      ],
      why: 'Minimum depth is the first leaf in level order, so BFS returns early while DFS must see everything. The recursive version has a trap: a node with one child is not a leaf, so plain 1 + min(left, right) is wrong.',
    },
    vars: 'n = number of nodes, w = widest level',
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(w)'],
    space: ['O(w)', 'O(1)', 'O(n²)', 'O(n log n)'],
    edgeCases: ['A node with exactly one child', 'A single node (depth 1)', 'Empty tree (0)'],
    approach: 'BFS level by level and return the level of the first node with no children. Recursively: when one side is null, return 1 + depth(other side).',
  },
  {
    slug: 'populating-next-right-pointers-in-each-node', id: 116, title: 'Populating Next Right Pointers in Each Node', difficulty: 'Medium', pattern: 'tree-bfs',
    brute: { text: 'BFS with a queue, linking each node to the next one in its level.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'The tree is perfect. How do you link each level using O(1) extra space?',
      options: [
        'Walk each level using the links you just built on it',
        'Run a BFS with a queue, linking each node to the next one',
        'Link node.left to node.right only, since the tree is perfect',
        'Do an in-order traversal and connect consecutive nodes',
      ],
      why: 'Once a level is linked it can be walked for free: set left.next = right, and right.next = next.left to bridge the gap between siblings — the part that linking within a parent misses. A queue solves it too, but costs O(width).',
    },
    vars: 'n = number of nodes',
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'],
    space: ['O(1)', 'O(n)', 'O(log n)', 'O(width)'],
    edgeCases: ['The rightmost node of each level points to null', 'A single node', 'Empty tree'],
    approach: 'head = root. While head.left != null: walk the level with node — node.left.next = node.right; if node.next != null, node.right.next = node.next.left. Then head = head.left.',
  },
  {
    slug: 'last-stone-weight', id: 1046, title: 'Last Stone Weight', difficulty: 'Easy', pattern: 'heap',
    brute: { text: 'Sort the stones again after every smash.', time: ['O(n² log n)', 'O(n log n)', 'O(n²)', 'O(n)'] },
    insight: {
      q: 'Which structure fits "take the two heaviest, put back the difference"?',
      options: [
        'A max-heap: poll twice and push the difference when it is not zero',
        'A sorted array, re-sorted after every smash',
        'A queue processed in the original order',
        'The total weight, reduced by the largest stone each round',
      ],
      why: 'Every round needs the two largest values of a collection that keeps changing, which is what a priority queue is for: O(log n) per operation instead of re-sorting. In Java: new PriorityQueue<>(Comparator.reverseOrder()).',
    },
    time: ['O(n log n)', 'O(n²)', 'O(n)', 'O(n² log n)'],
    space: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    edgeCases: ['Equal stones destroy each other', 'A single stone', 'Every stone destroyed (answer 0)'],
    approach: 'Max-heap of all stones. While more than one remains, poll a and b and push a − b when non-zero. Return the last stone, or 0.',
  },
  {
    slug: 'reorganize-string', id: 767, title: 'Reorganize String', difficulty: 'Medium', pattern: 'heap',
    alsoAccept: ['greedy'],
    brute: { text: 'Try every arrangement of the letters until one has no equal neighbours.', time: ['O(n!)', 'O(n log n)', 'O(n²)', 'O(n)'] },
    insight: {
      q: 'How do you space out the repeated letters?',
      options: [
        'Always place the most frequent letter that was not used last',
        'Shuffle the letters until no two neighbours match',
        'Place the letters alphabetically, skipping any repeat',
        'Return "" as soon as any letter occurs twice',
      ],
      why: 'Taking the commonest remaining letter (never the one just placed) always works, and it is impossible exactly when one letter exceeds (n + 1) / 2. A max-heap by remaining count makes each step cheap.',
    },
    vars: 'n = length of s; the alphabet is 26 letters',
    time: ['O(n)', 'O(n!)', 'O(n²)', 'O(n log n)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['One letter over half the length (return "")', 'All letters distinct', 'A single character'],
    approach: 'Count the letters into a max-heap by count. Poll the top; if it is the letter just placed, poll the next instead; append it, decrement, and push both back.',
  },
];
