import type { CuratedProblem } from '../types.ts';

export const extraTechniqueProblems: CuratedProblem[] = [
  {
    slug: 'minimum-number-of-arrows-to-burst-balloons', id: 452, title: 'Minimum Number of Arrows to Burst Balloons', difficulty: 'Medium', pattern: 'intervals',
    alsoAccept: ['greedy'],
    brute: { text: 'Try every set of shooting points and keep the smallest that works.', time: ['O(2ⁿ)', 'O(n²)', 'O(n log n)', 'O(n)'] },
    insight: {
      q: 'How few arrows burst every balloon?',
      options: [
        'Sort by END and shoot at the first end each time',
        'Sort by start and shoot an arrow at each start in turn',
        'Shoot through the middle of the widest balloon first',
        'One arrow per balloon that overlaps nothing, plus one for the rest',
      ],
      why: 'Shooting at the earliest end pops that balloon plus everything covering that point, and no earlier position could pop more. It is the same exchange argument as the non-overlapping intervals problem: arrows equal the number of restarts.',
    },
    time: ['O(n log n)', 'O(n)', 'O(n²)', 'O(n log max)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Touching balloons [[1,2],[2,3]] share an arrow', 'Coordinates near the int limits: compare, never subtract', 'A single balloon'],
    approach: 'Sort by end. arrows = 1 and last = the first end. For each balloon, if its start > last then arrows++ and last = its end.',
  },
  {
    slug: 'my-calendar-i', id: 729, title: 'My Calendar I', difficulty: 'Medium', pattern: 'intervals',
    brute: { text: 'Scan every existing booking on each new booking.', time: ['O(n) per booking', 'O(log n) per booking', 'O(1) per booking', 'O(n log n) per booking'] },
    insight: {
      q: 'How do you reject a booking that clashes with an existing one?',
      options: [
        'Keep bookings sorted and check only the two neighbours',
        'Scan every existing booking looking for an overlap',
        'Track the latest end time and compare new bookings with it',
        'Keep a boolean per minute and mark the whole range',
      ],
      why: 'Half-open intervals clash when one starts before the other ends, and once bookings are sorted only the one just before and just after can clash — a TreeMap answers both in O(log n). A full scan is O(n) per booking.',
    },
    vars: 'n = bookings made so far',
    time: ['O(log n) per booking', 'O(n) per booking', 'O(n log n) per booking', 'O(1) per booking'],
    space: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'],
    edgeCases: ['[10,20) and [20,30) do not clash', 'A booking entirely inside another', 'The first booking always succeeds'],
    approach: 'TreeMap<start, end>. prev = floorKey(start) clashes when its end > start; next = ceilingKey(start) clashes when next < end. Otherwise put(start, end).',
  },
  {
    slug: 'assign-cookies', id: 455, title: 'Assign Cookies', difficulty: 'Easy', pattern: 'greedy',
    brute: { text: 'Try every assignment of cookies to children.', time: ['O(n!)', 'O(n²)', 'O(n log n)', 'O(n)'] },
    insight: {
      q: 'How do you satisfy as many children as possible?',
      options: [
        'Sort both, then spend the smallest cookie that works',
        'Sort both and give the greediest child the largest cookie',
        'Give every child the cookie closest to their greed factor',
        'Count the cookies at least as large as each greed factor',
      ],
      why: 'Spending the smallest workable cookie keeps bigger ones available for greedier children, and swapping any other choice for it never satisfies fewer. Two pointers over the sorted arrays do the whole thing in one pass.',
    },
    vars: 'n = children, m = cookies',
    time: ['O(n log n + m log m)', 'O(n · m)', 'O(n + m)', 'O(n²)'],
    space: ['O(1)', 'O(n)', 'O(n + m)', 'O(log n)'],
    edgeCases: ['No cookie fits any child', 'More cookies than children', 'Equal size and greed counts as satisfied'],
    approach: 'Sort g and s. i = j = 0; while i < n and j < m: if s[j] >= g[i] then i++; j++ either way. The answer is i.',
  },
  {
    slug: 'hand-of-straights', id: 846, title: 'Hand of Straights', difficulty: 'Medium', pattern: 'greedy',
    brute: { text: 'Try every way of splitting the cards into groups of k.', time: ['O(n!)', 'O(n²)', 'O(n log n)', 'O(n · k)'] },
    insight: {
      q: 'How do you check the hand splits into consecutive groups of size k?',
      options: [
        'Always open a group at the smallest card left',
        'Sort the hand and cut it into consecutive blocks of k',
        'Check that every value occurs the same number of times',
        'Check the size divides by k and the values form one long run',
      ],
      why: 'The smallest remaining card has to open a group — nothing smaller can cover it — so its group is forced, and failing to find the next value means failure overall. A TreeMap of counts makes "smallest" and "decrement" cheap.',
    },
    vars: 'n = number of cards',
    time: ['O(n log n)', 'O(n · k)', 'O(n)', 'O(n²)'],
    space: ['O(n)', 'O(1)', 'O(k)', 'O(n²)'],
    edgeCases: ['n not divisible by k (false)', 'Duplicate values', 'k = 1 (always true)'],
    approach: 'Count cards into a TreeMap. While it is non-empty take the smallest key x and decrement x, x+1, … x+k−1, returning false if any is missing; drop keys that reach zero.',
  },
  {
    slug: 'letter-combinations-of-a-phone-number', id: 17, title: 'Letter Combinations of a Phone Number', difficulty: 'Medium', pattern: 'backtracking',
    brute: { text: 'Build every string of that length from all 26 letters, then filter.', time: ['O(26ⁿ · n)', 'O(4ⁿ · n)', 'O(n!)', 'O(n²)'] },
    insight: {
      q: 'How do you produce every letter combination?',
      options: [
        'Recurse digit by digit, appending each letter and removing it afterwards',
        'Generate every permutation of all the letters involved',
        'Pick a random letter per digit until all combinations have appeared',
        'Concatenate all the letters and take every substring of that length',
      ],
      why: "The digits form a decision tree: level i picks one letter of digit i, so each root-to-leaf path is a combination. Building it with a queue level by level works just as well; the count is the product of the digits' letter counts.",
    },
    vars: 'n = number of digits, each mapping to 3 or 4 letters',
    time: ['O(4ⁿ · n)', 'O(n!)', 'O(n²)', 'O(2ⁿ)'],
    space: ['O(n)', 'O(4ⁿ)', 'O(1)', 'O(n²)'],
    edgeCases: ['Empty input returns an empty list', '7 and 9 have four letters', 'A single digit'],
    approach: 'backtrack(index, sb): at index == digits.length() record sb.toString(); otherwise for each letter of that digit append, recurse with index + 1, and delete the last character.',
  },
  {
    slug: 'combination-sum-ii', id: 40, title: 'Combination Sum II', difficulty: 'Medium', pattern: 'backtracking',
    brute: { text: 'Generate every subset, keep those summing to the target, then deduplicate.', time: ['O(n log n · 2ⁿ)', 'O(n · 2ⁿ)', 'O(2ⁿ)', 'O(n²)'] },
    insight: {
      q: 'Numbers may be used once and the input has duplicates. How do you avoid duplicate combinations?',
      options: [
        'Sort, recurse with i + 1, and skip repeats at the same depth',
        'Recurse with i so values can repeat, then deduplicate after',
        'Strip the duplicate values out of the input before starting',
        'Keep chosen values in a set and skip anything already used',
      ],
      why: 'Recursing with i + 1 enforces "each number once"; the skip stops two branches at the same depth from starting with the same value, which is exactly what produces duplicate combinations. Removing duplicates outright would lose [1,1] for target 2.',
    },
    vars: 'n = number of candidates',
    time: ['O(n · 2ⁿ)', 'O(n!)', 'O(n²)', 'O(2ⁿ / n)'],
    space: ['O(n)', 'O(2ⁿ)', 'O(1)', 'O(n²)'],
    edgeCases: ['Duplicates that must both be used ([1,1], target 2)', 'Candidates larger than the target', 'No combination at all'],
    approach: 'Sort. backtrack(start, remaining): record on remaining == 0; for i from start: skip when i > start && c[i] == c[i−1]; break when c[i] > remaining; choose, recurse(i + 1, remaining − c[i]), un-choose.',
  },
];

export const extraGraphProblems: CuratedProblem[] = [
  {
    slug: 'surrounded-regions', id: 130, title: 'Surrounded Regions', difficulty: 'Medium', pattern: 'graph-traversal',
    alsoAccept: ['union-find'],
    brute: { text: 'For every O cell, run a fresh search asking whether it can reach the border.', time: ['O((m · n)²)', 'O(m · n)', 'O(m + n)', 'O(m · n · log(m · n))'] },
    insight: {
      q: 'Which regions of O survive?',
      options: [
        'Only those touching the border — flood inward from it',
        'Only the regions that are bigger than a single cell',
        'Regions whose cells each have at least two O neighbours',
        'Regions that lie in the middle rows and columns of the board',
      ],
      why: 'A region is captured unless it reaches an edge, so marking everything reachable from the border O cells and flipping what remains needs one pass each. Starting inside means undoing work whenever a region turns out to touch the edge.',
    },
    vars: 'm × n board',
    time: ['O(m · n)', 'O((m · n)²)', 'O(m + n)', 'O(m · n · log(m · n))'],
    space: ['O(m · n)', 'O(1)', 'O(m + n)', 'O((m · n)²)'],
    edgeCases: ['A single row or column captures nothing', 'No O cells at all', 'A region touching only a corner'],
    approach: "DFS or BFS from every border O, marking it safe (say '#'). Then turn every remaining O into X and every '#' back into O.",
  },
  {
    slug: 'shortest-path-in-binary-matrix', id: 1091, title: 'Shortest Path in Binary Matrix', difficulty: 'Medium', pattern: 'graph-traversal',
    brute: { text: 'Explore every clear path with DFS and keep the shortest.', time: ['O(8^(n²))', 'O(n²)', 'O(n⁴)', 'O(n² log n)'] },
    insight: {
      q: 'How do you find the shortest clear path when moves go in 8 directions?',
      options: [
        'BFS from the top-left over all 8 neighbours, counting cells',
        'DFS, keeping the shortest path it happens to find',
        'Dijkstra, because diagonal steps cost more than straight ones',
        'Move greedily toward the corner, backtracking when blocked',
      ],
      why: 'Every move costs one cell, so plain BFS gives the shortest path and the diagonals are just extra neighbours. Return −1 when the queue empties, and check the starting cell before anything else.',
    },
    vars: 'n × n grid',
    time: ['O(n²)', 'O(n⁴)', 'O(n² log n)', 'O(8ⁿ)'],
    space: ['O(n²)', 'O(1)', 'O(n)', 'O(n⁴)'],
    edgeCases: ['Start or end blocked (−1)', 'A 1×1 grid', 'No path at all'],
    approach: 'If grid[0][0] != 0 return −1. BFS with distance 1 at the start, visiting the 8 neighbours that hold 0 and marking them visited; return the distance on reaching the bottom-right.',
  },
  {
    slug: 'course-schedule-iv', id: 1462, title: 'Course Schedule IV', difficulty: 'Medium', pattern: 'topological-sort',
    brute: { text: 'Run a fresh search through the graph for every query.', time: ['O(q · (V + E))', 'O(V · E + q)', 'O(V + E + q)', 'O(V³)'] },
    insight: {
      q: 'How do you answer many "is X a prerequisite of Y?" queries?',
      options: [
        'Compute reachability once: topological order plus set union',
        'Run a fresh DFS for every query against the whole graph',
        'Compare the two courses\' positions in a topological order',
        'Check whether a direct prerequisite edge joins the two',
      ],
      why: 'Prerequisite means reachable, not adjacent, and coming earlier in some topological order does not imply a path. Computing the closure once answers every query in O(1) afterwards.',
    },
    vars: 'V = courses, E = prerequisite pairs, q = queries',
    time: ['O(V · E + q)', 'O(q · (V + E))', 'O(V + E + q)', 'O(V² log V)'],
    space: ['O(V²)', 'O(V + E)', 'O(q)', 'O(V)'],
    edgeCases: ['No prerequisites at all', 'Chains of three or more (transitivity)', 'A query about a course and itself'],
    approach: "Take Kahn's order; for each course union the reachable sets of its prerequisites (boolean[V][V] or bitsets). Each query is then a table lookup.",
  },
  {
    slug: 'find-all-possible-recipes-from-given-supplies', id: 2115, title: 'Find All Possible Recipes from Given Supplies', difficulty: 'Medium', pattern: 'topological-sort',
    brute: { text: 'Sweep every recipe again and again until a full pass changes nothing.', time: ['O(V · (V + E))', 'O(V + E)', 'O(V²)', 'O(2ⱽ)'] },
    insight: {
      q: 'How do you decide which recipes can be made?',
      options: [
        'Treat ingredients as prerequisites and peel in-degree zeros',
        'Check every recipe once against the list of supplies',
        'Sort recipes by how many ingredients they need and go in order',
        'Mark a recipe available as soon as one ingredient is supplied',
      ],
      why: 'Recipes can require other recipes, so this is a DAG: supplies are available from the start, and a recipe unlocks when its last missing ingredient appears. A single pass misses chains, and ingredient count says nothing about order.',
    },
    vars: 'V = recipes plus ingredients, E = ingredient links',
    time: ['O(V + E)', 'O(V · E)', 'O(V²)', 'O(E log V)'],
    space: ['O(V + E)', 'O(1)', 'O(V²)', 'O(E²)'],
    edgeCases: ['A recipe depending on another recipe', 'Recipes that depend on each other (never makeable)', 'An ingredient that is never supplied'],
    approach: 'in-degree[recipe] = its ingredient count; map each ingredient to the recipes that need it. Queue the supplies; popping an item decrements its dependents, and a recipe reaching zero is makeable and itself queued.',
  },
  {
    slug: 'satisfiability-of-equality-equations', id: 990, title: 'Satisfiability of Equality Equations', difficulty: 'Medium', pattern: 'union-find',
    brute: { text: 'Recheck every equation after each merge until nothing changes.', time: ['O(n²)', 'O(n)', 'O(n log n)', 'O(26ⁿ)'] },
    insight: {
      q: 'How do you check a mix of == and != constraints?',
      options: [
        'Union all == first, then test every != against it',
        'Process the equations in the order they are given',
        'Union both == and != pairs and then look for a cycle',
        'Count the equations of each kind and compare the totals',
      ],
      why: 'Equality is transitive, so all the == constraints must be merged before any != can be judged — checking in input order would wrongly accept "a!=c, a==b, b==c". With only 26 variables, Union-Find is trivial here.',
    },
    vars: 'n = number of equations; variables are the 26 lowercase letters',
    time: ['O(n · α(26))', 'O(n²)', 'O(n log n)', 'O(26ⁿ)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(26²)'],
    edgeCases: ['"a!=a" is always false', 'Chains: a==b, b==c, a!=c', 'Only != equations'],
    approach: 'UnionFind(26). First pass unions every "a==b". Second pass returns false for any "a!=b" with find(a) == find(b).',
  },
  {
    slug: 'most-stones-removed-with-same-row-or-column', id: 947, title: 'Most Stones Removed with Same Row or Column', difficulty: 'Medium', pattern: 'union-find',
    alsoAccept: ['graph-traversal'],
    brute: { text: 'Try every removal order and keep the longest one that works.', time: ['O(n!)', 'O(n²)', 'O(n log n)', 'O(n · α(n))'] },
    insight: {
      q: 'How many stones can be removed?',
      options: [
        'Stones minus the number of connected groups',
        'Stones minus the number of distinct rows that are used',
        'All but one overall, so the answer is stones minus one',
        'Every stone that shares a row or column with another one',
      ],
      why: 'Inside a connected group you can peel stones in reverse spanning-tree order, leaving exactly one, so the answer is n minus the group count. Sharing a row or column connects, which is what Union-Find tracks.',
    },
    vars: 'n = number of stones',
    time: ['O(n · α(n))', 'O(n²)', 'O(n log n)', 'O(n³)'],
    space: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'],
    edgeCases: ['A single stone (0 removals)', 'Every stone in one row', 'Two groups that never meet'],
    approach: 'Union each stone with its row id and its column id (offset columns by 10001 so the ids never collide). Count distinct roots among the stones; the answer is n − groups.',
  },
  {
    slug: 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid', id: 1368, title: 'Minimum Cost to Make at Least One Valid Path in a Grid', difficulty: 'Hard', pattern: 'shortest-path',
    alsoAccept: ['graph-traversal'],
    brute: { text: 'Try every route through the grid, counting the arrows changed.', time: ['O(4^(m·n))', 'O(m · n)', 'O(m · n · log(m · n))', 'O((m · n)²)'] },
    insight: {
      q: 'Following an arrow is free and changing one costs 1. What does that make it?',
      options: [
        '0-1 BFS with a deque: free moves in front, paid ones behind',
        'A plain BFS, since every cell is one step from its neighbour',
        'A DFS that counts the arrows it changes along the way',
        'A DP swept over the grid in reading order, row by row',
      ],
      why: 'Exactly two edge weights make this 0-1 BFS: a deque keeps cells in non-decreasing cost without a heap, so it runs in O(m·n). Dijkstra works too at O(m·n log(m·n)); plain BFS ignores that turning an arrow costs something.',
    },
    vars: 'm × n grid',
    time: ['O(m · n)', 'O(m · n · log(m · n))', 'O((m · n)²)', 'O(4^(m·n))'],
    space: ['O(m · n)', 'O(1)', 'O(m + n)', 'O((m · n)²)'],
    edgeCases: ['A grid that is already valid (cost 0)', 'A 1×1 grid', 'Every arrow pointing away from the target'],
    approach: 'dist = ∞ except dist[0][0] = 0; deque of cells. Pop the front; for each of the four directions the step costs 0 when the arrow already points that way, else 1; on improvement addFirst for 0 and addLast for 1.',
  },
  {
    slug: 'number-of-ways-to-arrive-at-destination', id: 1976, title: 'Number of Ways to Arrive at Destination', difficulty: 'Medium', pattern: 'shortest-path',
    brute: { text: 'Enumerate every path and count those taking the minimum time.', time: ['O(V!)', 'O(E log V)', 'O(V · E)', 'O(V + E)'] },
    insight: {
      q: 'How do you count the shortest paths rather than just measure one?',
      options: [
        'Dijkstra carrying a path counter alongside the distance',
        'Enumerate every path and keep those of minimum length',
        'Multiply the number of choices at each node along the way',
        'Run BFS and count how often the destination is reached',
      ],
      why: "Once a node is finalized its distance is fixed, so ways[v] collects from every u where dist[u] + w equals dist[v]. Listing all paths is exponential and BFS ignores the road times. Keep the counts modulo 1e9+7.",
    },
    vars: 'V = intersections, E = roads',
    time: ['O(E log V)', 'O(V · E)', 'O(V + E)', 'O(V³)'],
    space: ['O(V + E)', 'O(1)', 'O(V²)', 'O(E²)'],
    edgeCases: ['Times up to 1e9: keep distances in long', 'Several shortest paths meeting at one node', 'Counts taken modulo 1e9+7'],
    approach: 'Dijkstra from 0 with ways[0] = 1. When relaxing u → v: if dist[u] + w < dist[v], set the distance and ways[v] = ways[u]; if equal, ways[v] = (ways[v] + ways[u]) % MOD.',
  },
];

export const extraDpProblems: CuratedProblem[] = [
  {
    slug: 'min-cost-climbing-stairs', id: 746, title: 'Min Cost Climbing Stairs', difficulty: 'Easy', pattern: 'dp-1d',
    brute: { text: 'Recurse over both step sizes without memoizing.', time: ['O(2ⁿ)', 'O(n)', 'O(n²)', 'O(n log n)'] },
    insight: {
      q: 'What is the recurrence for the cheapest way to stand on step i?',
      options: [
        'best(i) = cost[i] + min(best(i − 1), best(i − 2))',
        'best(i) = cost[i] + best(i − 1), paying for every step passed',
        'best(i) = cost[i] + the cheapest of all earlier steps',
        'The total of the cheaper step in each adjacent pair',
      ],
      why: 'You reach step i from i − 1 or i − 2, so take the cheaper arrival and pay this step. The top is one past the last index, so the answer is min(best(n − 1), best(n − 2)), and starting at index 0 or 1 is free.',
    },
    time: ['O(n)', 'O(n²)', 'O(2ⁿ)', 'O(n log n)'],
    space: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
    edgeCases: ['Only two steps', 'Starting at index 1 can be cheaper', 'The top is one past the last index'],
    approach: 'Two rolling variables a and b holding the cost to stand on the previous two steps: next = min(a + cost[i−2], b + cost[i−1]). Return the value for i = n.',
  },
  {
    slug: 'perfect-squares', id: 279, title: 'Perfect Squares', difficulty: 'Medium', pattern: 'dp-1d',
    alsoAccept: ['graph-traversal'],
    brute: { text: 'Recurse over every square at every remaining value, without memoizing.', time: ['O(√nⁿ)', 'O(n √n)', 'O(n²)', 'O(n log n)'] },
    insight: {
      q: 'Which recurrence gives the fewest perfect squares summing to n?',
      options: [
        'dp[i] = 1 + min over squares s ≤ i of dp[i − s]',
        'Subtract the largest square that fits, then repeat',
        'dp[i] = dp[i − 1] + 1',
        'The number of distinct squares below n',
      ],
      why: 'The last square used is some s, leaving i − s to cover optimally — coin change with squares as coins. Greedy fails on 12: it takes 9 + 1 + 1 + 1 while 4 + 4 + 4 needs three.',
    },
    vars: 'n = the target number',
    time: ['O(n √n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'],
    space: ['O(n)', 'O(1)', 'O(√n)', 'O(n²)'],
    edgeCases: ['n is itself a square (answer 1)', 'n = 1', "Lagrange's theorem: the answer is never above 4"],
    approach: 'dp[0] = 0; for i from 1 to n, dp[i] = 1 + min(dp[i − s]) over squares s ≤ i. A BFS over remaining values gives the same answer level by level.',
  },
  {
    slug: 'minimum-path-sum', id: 64, title: 'Minimum Path Sum', difficulty: 'Medium', pattern: 'dp-2d',
    brute: { text: 'Recurse over both moves from every cell without memoizing.', time: ['O(2^(m+n))', 'O(m · n)', 'O(m + n)', 'O((m · n)²)'] },
    insight: {
      q: 'What is the recurrence for the cheapest path into cell (r, c)?',
      options: [
        'grid[r][c] + min(best(r − 1, c), best(r, c − 1))',
        'grid[r][c] + the minimum over every cell above and to the left',
        'The sum of the smallest value in each row',
        'Step to the cheaper of the two neighbours at every move',
      ],
      why: 'You can only arrive from above or from the left, so the cheaper arrival plus this cell is optimal. Greedy stepping fails as soon as a cheap cell leads into an expensive row, and one rolling row is all the memory needed.',
    },
    vars: 'm × n grid; DP over a single rolling row',
    time: ['O(m · n)', 'O(m + n)', 'O((m · n)²)', 'O(2^(m+n))'],
    space: ['O(n)', 'O(m · n)', 'O(1)', 'O(2^(m+n))'],
    edgeCases: ['A single row or column', 'A 1×1 grid', 'All values equal'],
    approach: 'row = prefix sums of the first grid row. For each later row: row[0] += grid[r][0]; for c ≥ 1 row[c] = grid[r][c] + min(row[c], row[c−1]). Return row[n−1].',
  },
  {
    slug: 'interleaving-string', id: 97, title: 'Interleaving String', difficulty: 'Medium', pattern: 'dp-2d',
    brute: { text: 'Recurse over taking from s1 or s2 at each step, without memoizing.', time: ['O(2^(m+n))', 'O(m · n)', 'O(m + n)', 'O(m² · n²)'] },
    insight: {
      q: 'What does dp[i][j] mean here?',
      options: [
        's3\'s first i + j characters interleave s1[0..i) and s2[0..j)',
        'The length of the longest common subsequence of s1 and s2',
        'Whether the characters s1[i] and s2[j] happen to be equal',
        'How many ways the first i + j characters can be split up',
      ],
      why: 'The last character came from s1 or from s2, so dp[i][j] = (dp[i−1][j] && s1[i−1] == s3[i+j−1]) || (dp[i][j−1] && s2[j−1] == s3[i+j−1]). Matching greedily fails whenever both strings offer the same next character.',
    },
    vars: 'm, n = lengths of s1 and s2; DP over a rolling row',
    time: ['O(m · n)', 'O(m + n)', 'O(2^(m+n))', 'O(m² · n²)'],
    space: ['O(n)', 'O(m · n)', 'O(1)', 'O(m + n)'],
    edgeCases: ['|s1| + |s2| != |s3| (false immediately)', 'Empty strings', 'Both strings offering the same next character'],
    approach: 'Return false when the lengths disagree. Roll a row over s1: dp[j] = (dp[j] && s1[i−1] == s3[i+j−1]) || (dp[j−1] && s2[j−1] == s3[i+j−1]), seeding the first row and column from prefix matches.',
  },
  {
    slug: 'longest-word-in-dictionary', id: 720, title: 'Longest Word in Dictionary', difficulty: 'Medium', pattern: 'trie',
    alsoAccept: ['hashing'],
    brute: { text: 'For each word, look every prefix up in a set of all the words.', time: ['O(N · L)', 'O(N)', 'O(N log N)', 'O(2^N)'] },
    insight: {
      q: 'How do you find the longest word that can be built one letter at a time?',
      options: [
        'Insert every word in a trie and DFS only through nodes that end a word',
        'Sort by length and return the longest word',
        'Return the word whose prefixes appear most often in the list',
        'Compare each word against a set of the others, in any order',
      ],
      why: 'A word qualifies only if every prefix of it is also a word, which a trie checks as it descends: stop the moment a node is not a word end. Visiting children in alphabetical order makes the first deepest word the right tie-break.',
    },
    vars: 'N = total characters across all words',
    time: ['O(N)', 'O(N log N)', 'O(N²)', 'O(2^N)'],
    space: ['O(N)', 'O(1)', 'O(N²)', 'O(log N)'],
    edgeCases: ['Ties broken alphabetically', 'No single-letter word (answer "")', 'Duplicate words'],
    approach: 'Insert all words into a trie. DFS from the root over children a..z, descending only where isWord is set, and keep the deepest word reached.',
  },
  {
    slug: 'map-sum-pairs', id: 677, title: 'Map Sum Pairs', difficulty: 'Medium', pattern: 'trie',
    brute: { text: 'Scan every stored key on each sum(prefix) call.', time: ['O(N · L) per sum', 'O(L) per sum', 'O(log N) per sum', 'O(N) per insert'] },
    insight: {
      q: 'How do you keep sum(prefix) fast when a key can be inserted again with a new value?',
      options: [
        'Keep a running total per node and push only the delta',
        'Add the new value to every node on the path each time',
        'Walk the whole subtree under the prefix on every sum call',
        'Keep the keys in a hash map and scan them on each query',
      ],
      why: 'Re-inserting a key must not double count, so remember its old value and propagate (new − old). Then sum(prefix) is one walk to that node — O(key length) rather than O(number of keys).',
    },
    vars: 'L = key length, N = keys stored',
    time: ['O(L) per insert and per sum', 'O(N · L) per sum', 'O(N) per insert', 'O(L²) per sum'],
    space: ['O(N · L)', 'O(1)', 'O(L)', 'O(N²)'],
    edgeCases: ['Re-inserting a key with a different value', 'A prefix matching no key (0)', 'A key that is a prefix of another'],
    approach: 'A HashMap holds each key\'s current value. insert: delta = val − old; walk the trie adding delta to every node on the path. sum: walk to the prefix node and return its total.',
  },
  {
    slug: 'reverse-bits', id: 190, title: 'Reverse Bits', difficulty: 'Easy', pattern: 'bit-manipulation',
    brute: { text: 'Build the binary string, reverse it, and parse it back.', time: ['O(32)', 'O(n)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'How do you reverse all 32 bits?',
      options: [
        'Shift the result left, OR in n\'s lowest bit, shift n right',
        'Reverse the decimal digits and convert the result back',
        'Subtract the number from 2³² − 1 to flip every bit',
        'Swap the two 16-bit halves, which mirrors the value',
      ],
      why: 'Peeling the lowest bit off n and pushing it into the result reverses the order one bit per step. Use >>> rather than >>, or the sign bit repeats, and remember Java has no unsigned int, so the result can read as negative.',
    },
    vars: 'the input is a 32-bit integer',
    time: ['O(1) (32 steps)', 'O(n)', 'O(log n)', 'O(32²)'],
    space: ['O(1)', 'O(32)', 'O(n)', 'O(log n)'],
    edgeCases: ['The top bit set gives a negative result in Java', 'n = 0', 'Repeated calls: cache byte-sized reversals'],
    approach: 'result = 0; repeat 32 times: result = (result << 1) | (n & 1); n >>>= 1. Return result.',
  },
  {
    slug: 'single-number-ii', id: 137, title: 'Single Number II', difficulty: 'Medium', pattern: 'bit-manipulation',
    brute: { text: 'Count every value in a hash map and find the one appearing once.', time: ['O(n)', 'O(n²)', 'O(n log n)', 'O(1)'] },
    insight: {
      q: 'Every value appears three times except one. Why does plain XOR fail?',
      options: [
        'XOR cancels pairs, not triples: count each bit position modulo 3 instead',
        'XOR fails on negative numbers, so take absolute values first',
        'It works if you XOR the array twice over',
        'XOR needs a sorted array to cancel correctly',
      ],
      why: 'Three copies leave one behind under XOR. Counting how many numbers set each of the 32 bits and keeping the bits whose count is not a multiple of 3 rebuilds the odd value; the ones/twos state machine does the same with two variables.',
    },
    time: ['O(n)', 'O(n log n)', 'O(n²)', 'O(32ⁿ)'],
    space: ['O(1)', 'O(n)', 'O(32)', 'O(log n)'],
    edgeCases: ['Negative numbers (the sign bit counts too)', 'A single-element array', 'The unique value may be 0'],
    approach: 'For each bit 0..31 count how many numbers set it and set that bit in the answer when the count % 3 != 0. Equivalent: ones = (ones ^ x) & ~twos; twos = (twos ^ x) & ~ones.',
  },
];
