import { describe, expect, it } from 'vitest';
import { animationFor, ANIMATED_PATTERNS } from '../shared/animations/index.ts';
import type { Layer } from '../shared/animations/index.ts';
import { PATTERN_IDS } from '../shared/types.ts';

/**
 * Every animation is generated by running the algorithm, so these hold each one
 * to the answer that algorithm must produce. If a generator ever draws a wrong
 * step, its result drifts and the test says which pattern.
 */
const EXPECTED: Record<string, string> = {
  hashing: '(1, 3)', // 8 + 2 = 10, found when the 2 at index 3 looks up 8
  'two-pointers': '(4, 6)',
  'sliding-window': '4', // "cbad"
  'prefix-sum': '11', // 1 + 4 + 1 + 5
  'binary-search': '5',
  stack: 'true',
  'monotonic-stack': '5,5,6,6,-1,-1',
  'linked-list': '4→3→2→1',
  'fast-slow': 'cycle at 3',
  'tree-dfs': '3',
  'tree-bfs': '[1][2,3][4,5,6]',
  heap: '5', // 3rd largest of 3,1,5,12,2,11
  intervals: '[1,6] [8,10] [15,18]',
  greedy: 'true',
  backtracking: '8',
  'graph-traversal': '4',
  'topological-sort': 'ABCDE',
  'union-find': '2 components, redundant 2–0',
  'shortest-path': 'A0 B3 C1 D4 E7',
  'dp-1d': '12', // 2 + 9 + 1
  'dp-2d': '10', // C(5, 2)
  trie: 'ca:true cow:false',
  'bit-manipulation': '4',
};

describe('pattern animations', () => {
  it('cover every pattern in the app', () => {
    expect([...ANIMATED_PATTERNS].sort()).toEqual([...PATTERN_IDS].sort());
  });

  it.each(PATTERN_IDS.map((id) => [id] as const))('%s computes the right answer', (id) => {
    expect(animationFor(id).result).toBe(EXPECTED[id]);
  });

  it.each(PATTERN_IDS.map((id) => [id] as const))('%s is watchable: several steps, each explained', (id) => {
    const a = animationFor(id);
    expect(a.pattern).toBe(id);
    expect(a.title.trim()).not.toBe('');
    expect(a.setup.trim()).not.toBe('');
    expect(a.takeaway.trim()).not.toBe('');
    expect(a.frames.length, `${id} has too few frames to animate`).toBeGreaterThanOrEqual(4);
    expect(a.frames.length, `${id} drags on`).toBeLessThanOrEqual(40);
    for (const [k, f] of a.frames.entries()) {
      expect(f.caption.trim(), `${id} frame ${k} has no caption`).not.toBe('');
      expect(f.layers.length, `${id} frame ${k} draws nothing`).toBeGreaterThan(0);
      expect(f.caption, `${id} frame ${k} leaks a JS value`).not.toMatch(/undefined|NaN|\[object/);
    }
  });

  it.each(PATTERN_IDS.map((id) => [id] as const))('%s only draws what it can render', (id) => {
    const check = (l: Layer) => {
      if (l.kind === 'array') {
        for (const m of l.markers ?? []) expect(m.at, `${id}: marker ${m.label}`).toBeLessThan(Math.max(1, l.cells.length));
        for (const s of l.spans ?? []) {
          expect(s.from).toBeGreaterThanOrEqual(0);
          expect(s.to).toBeLessThan(l.cells.length);
          expect(s.from).toBeLessThanOrEqual(s.to);
        }
      }
      if (l.kind === 'graph') {
        const ids = new Set(l.nodes.map((n) => n.id));
        expect(ids.size, `${id}: duplicate node ids`).toBe(l.nodes.length);
        for (const e of l.edges) {
          expect(ids.has(e.from), `${id}: edge from missing ${e.from}`).toBe(true);
          expect(ids.has(e.to), `${id}: edge to missing ${e.to}`).toBe(true);
        }
        for (const n of l.nodes) {
          expect(n.x).toBeGreaterThanOrEqual(0);
          expect(n.x).toBeLessThanOrEqual(100);
          expect(n.y).toBeGreaterThanOrEqual(0);
          expect(n.y).toBeLessThanOrEqual(100);
        }
      }
      if (l.kind === 'list') {
        expect(l.next.length).toBe(l.nodes.length);
        for (const t of l.next) if (t != null) expect(t).toBeLessThan(l.nodes.length);
      }
      if (l.kind === 'grid') {
        const width = l.rows[0]?.length ?? 0;
        for (const row of l.rows) expect(row.length).toBe(width);
      }
    };
    for (const f of animationFor(id).frames) f.layers.forEach(check);
  });

  it('builds each animation once and reuses it', () => {
    expect(animationFor('hashing')).toBe(animationFor('hashing'));
  });
});
