import type { FormulaGroup } from './types.ts';

/** The arithmetic that turns up inside complexity arguments and counting problems. */
export const FORMULAS: FormulaGroup[] = [
  {
    group: 'Series and sums',
    blurb: 'Where the n² in a nested loop actually comes from.',
    formulas: [
      { name: 'First n integers', expression: '1 + 2 + … + n = n(n + 1) / 2 = Θ(n²)', useFor: 'A loop whose inner bound depends on the outer index — the classic "why is this O(n²)".' },
      { name: 'First n squares', expression: '1² + 2² + … + n² = n(n + 1)(2n + 1) / 6 = Θ(n³)', useFor: 'Triple-nested bounds; total work over all subarrays.' },
      { name: 'Arithmetic series', expression: 'n terms, first a, last l → n(a + l) / 2', useFor: 'Any evenly spaced total.' },
      { name: 'Geometric series', expression: '1 + 2 + 4 + … + 2^k = 2^(k+1) − 1 ≈ 2ⁿ', useFor: 'Why doubling an ArrayList is O(1) amortised: the copies sum to less than 2n.' },
      { name: 'Geometric, ratio < 1', expression: '1 + r + r² + … = 1 / (1 − r) for |r| < 1', useFor: 'Halving recursions: n + n/2 + n/4 + … = 2n, so the total is Θ(n), not Θ(n log n).' },
      { name: 'Harmonic series', expression: '1 + 1/2 + 1/3 + … + 1/n ≈ ln n', useFor: 'Sieve of Eratosthenes: Θ(n log log n). Also why "for each i, step by i" is Θ(n log n).' },
      { name: 'Number of subarrays', expression: 'n(n + 1) / 2', useFor: 'Brute force over every contiguous range is Θ(n²) ranges — Θ(n³) if you re-sum each one.' },
    ],
  },
  {
    group: 'Counting',
    blurb: 'How big the search space is — which tells you whether backtracking will survive.',
    formulas: [
      { name: 'Subsets', expression: '2ⁿ', useFor: 'Every subset of n items. n ≤ 20 or so for a brute force.' },
      { name: 'Permutations', expression: 'n! ', useFor: 'Every ordering. n ≤ 10 in practice; 10! is 3.6 million, 12! is 479 million.' },
      { name: 'Combinations', expression: 'C(n, k) = n! / (k!(n − k)!)', useFor: 'Choosing k of n, order irrelevant. Also the grid-paths answer: C(m + n − 2, m − 1).' },
      { name: "Pascal's rule", expression: 'C(n, k) = C(n − 1, k − 1) + C(n − 1, k)', useFor: 'The recurrence behind Pascal\'s triangle, and the dp transition for counting paths.' },
      { name: 'k-ary strings', expression: 'kⁿ', useFor: 'Phone-keypad letter combinations: 4ⁿ worst case. Board search: 4 directions to depth L.' },
      { name: 'Catalan number', expression: 'C(n) = (2n choose n) / (n + 1)', useFor: 'Valid bracket sequences, distinct BSTs of n nodes, ways to triangulate. Grows ~4ⁿ / n^1.5.' },
      { name: 'Pigeonhole', expression: 'n + 1 items in n boxes → some box has 2', useFor: 'Proving a duplicate must exist — find-the-duplicate-number, and cycle arguments.' },
    ],
  },
  {
    group: 'Logs and powers',
    blurb: 'Why "halve it every step" is log n, and how to size an input.',
    formulas: [
      { name: 'Halving', expression: 'n → n/2 → n/4 → … → 1 takes log₂ n steps', useFor: 'Binary search, balanced tree height, heap sift.' },
      { name: 'Log identities', expression: 'log(ab) = log a + log b; log(aᵏ) = k log a; log_b n = log n / log b', useFor: 'Why the base does not matter in Big-O: it is a constant factor.' },
      { name: 'Powers of two', expression: '2¹⁰ ≈ 10³, 2²⁰ ≈ 10⁶, 2³⁰ ≈ 10⁹', useFor: 'log₂(10⁶) ≈ 20, log₂(10⁹) ≈ 30. Binary search over a billion is 30 steps.' },
      { name: 'int and long range', expression: 'int ≈ ±2.1 × 10⁹ (2³¹), long ≈ ±9.2 × 10¹⁸ (2⁶³)', useFor: 'If a product can exceed 2 × 10⁹, you need long.' },
      { name: 'Tree height', expression: 'balanced: ⌊log₂ n⌋; degenerate: n − 1', useFor: 'Why BST operations are "O(h), which is O(log n) only if balanced".' },
      { name: 'Nodes in a full tree', expression: 'height h holds 2^(h+1) − 1 nodes; level h holds 2^h', useFor: 'Sizing a heap array and level-order buffers.' },
    ],
  },
  {
    group: 'Modular and number theory',
    blurb: 'For the "answer may be large, return it modulo 10⁹ + 7" problems.',
    formulas: [
      { name: 'Mod distributes', expression: '(a + b) % m = ((a % m) + (b % m)) % m — same for ×', useFor: 'Take the modulus at every step so nothing overflows.' },
      { name: 'Mod does NOT distribute over division', expression: 'use the modular inverse: a / b mod m = a × b^(m−2) mod m for prime m', useFor: 'Combinatorics under 10⁹ + 7, which is prime.' },
      { name: 'Non-negative modulus', expression: '((x % m) + m) % m, or Math.floorMod(x, m)', useFor: 'Circular arrays and hashing with negative values.' },
      { name: 'GCD (Euclid)', expression: 'gcd(a, b) = gcd(b, a % b), gcd(a, 0) = a — O(log min(a, b))', useFor: 'Fractions, line-slope keys, "can these be evenly grouped".' },
      { name: 'LCM', expression: 'lcm(a, b) = a / gcd(a, b) × b', useFor: 'Divide before multiplying, or you overflow.' },
      { name: 'Primes up to n', expression: 'Sieve of Eratosthenes — Θ(n log log n) time, Θ(n) space', useFor: 'Count-primes, and anything needing many primality tests.' },
      { name: 'Trial division', expression: 'test divisors up to √n only', useFor: 'One-off primality or factor enumeration: O(√n).' },
    ],
  },
  {
    group: 'Sizing the input',
    blurb: 'Constraints tell you the intended complexity. Read them before you design.',
    formulas: [
      { name: 'n ≤ 10', expression: 'O(n!) or O(2ⁿ · n) is fine', useFor: 'Permutations, full backtracking.' },
      { name: 'n ≤ 20–25', expression: 'O(2ⁿ)', useFor: 'Subset enumeration, bitmask DP.' },
      { name: 'n ≤ 500', expression: 'O(n³)', useFor: 'Floyd–Warshall, interval DP.' },
      { name: 'n ≤ 5,000', expression: 'O(n²)', useFor: 'Nested loops, edit-distance-style DP.' },
      { name: 'n ≤ 10⁶', expression: 'O(n log n)', useFor: 'Sorting, heaps, binary search over the answer.' },
      { name: 'n ≥ 10⁷', expression: 'O(n) or O(log n)', useFor: 'One pass, two pointers, maths.' },
      { name: 'Rule of thumb', expression: '≈ 10⁸ simple operations per second', useFor: 'Multiply your complexity by the constraint. If it clears 10⁸, expect a timeout.' },
    ],
  },
  {
    group: 'Number theory, further',
    blurb: 'The integer tricks behind pow(x, n), "return it modulo 10⁹ + 7", and anything about divisors.',
    formulas: [
      { name: 'Fast exponentiation', expression: 'aⁿ = (a^(n/2))² for even n, a · aⁿ⁻¹ for odd — O(log n) multiplications', useFor: 'pow(x, n) and modular powers. Square and halve instead of multiplying n times.' },
      { name: 'Modular inverse', expression: 'for prime m: a⁻¹ ≡ a^(m − 2) (mod m), by Fermat', useFor: 'Dividing under 10⁹ + 7 — nCr mod p. Compute it with fast exponentiation.' },
      { name: 'Ceiling division', expression: '⌈a / b⌉ = (a + b − 1) / b for positive integers', useFor: 'Hours to eat a pile at speed k (Koko), pages per day, boxes needed — without floating point.' },
      { name: 'Prime factorisation', expression: 'divide out d = 2, 3, 4 … while d² ≤ n; any remainder > 1 is prime — O(√n)', useFor: 'Ugly numbers, counting divisors, simplifying fractions.' },
      { name: 'Number of divisors', expression: 'n = p₁^a₁ · p₂^a₂ ⋯ → (a₁ + 1)(a₂ + 1)⋯ divisors', useFor: '12 = 2² · 3 has (2 + 1)(1 + 1) = 6 divisors: 1, 2, 3, 4, 6, 12.' },
      { name: 'Digit count', expression: 'digits(n) = ⌊log₁₀ n⌋ + 1; peel digits with n % 10, then n / 10', useFor: 'Palindrome number, reverse integer, digit sums — the loop runs once per digit, O(log n).' },
      { name: 'Integer square root', expression: 'largest r with r² ≤ n: binary search r in [0, n], compare r * r as a long', useFor: 'sqrt(x) without floating point, perfect-square checks.' },
    ],
  },
  {
    group: 'Bases and bits',
    blurb: 'Numbers as bits: what the bit-manipulation problems assume you can do in your head.',
    formulas: [
      { name: 'Binary place values', expression: '1011₂ = 1·8 + 0·4 + 1·2 + 1·1 = 11', useFor: 'Reading and writing binary; bit i is worth 2ⁱ.' },
      { name: 'Base conversion', expression: 'digits of n in base b: repeat n % b, n /= b, then reverse', useFor: 'Excel column titles (base 26 with no zero), binary strings, base-7.' },
      { name: 'Bits needed', expression: 'n needs ⌊log₂ n⌋ + 1 bits', useFor: '10⁹ fits in 30 bits, so a bitmask over values up to 10⁹ needs a long only past bit 31.' },
      { name: "Two's complement", expression: '−x = ~x + 1, so −1 is all ones (0xFFFFFFFF)', useFor: 'Why >> on a negative keeps the sign and >>> is needed to shift in zeros.' },
      { name: 'Power-of-two test', expression: 'n > 0 && (n & (n − 1)) == 0', useFor: 'A power of two has one set bit; n − 1 flips it and every bit below.' },
      { name: 'Lowest set bit', expression: 'x & −x isolates it; x & (x − 1) clears it', useFor: 'Counting bits in O(set bits), Fenwick trees, splitting numbers by a differing bit (Single Number III).' },
      { name: 'XOR identities', expression: 'a ^ a = 0, a ^ 0 = a, and XOR is commutative and associative', useFor: 'Pairs cancel in any order — Single Number, Missing Number, swapping without a temp.' },
      { name: 'Hex digits', expression: 'one hex digit = 4 bits; 0xFF = 255, 0x7FFFFFFF = Integer.MAX_VALUE', useFor: 'Reading masks at a glance.' },
    ],
  },
  {
    group: 'Geometry',
    blurb: 'Points, lines and rectangles, kept in integers wherever possible so precision never bites.',
    formulas: [
      { name: 'Euclidean distance', expression: '√((x₁ − x₂)² + (y₁ − y₂)²) — compare the squares instead', useFor: 'K Closest Points: ordering by x² + y² gives the same order with no square root and no doubles.' },
      { name: 'Manhattan distance', expression: '|x₁ − x₂| + |y₁ − y₂|', useFor: 'Grid moves without diagonals; Min Cost to Connect All Points.' },
      { name: 'Chebyshev distance', expression: 'max(|x₁ − x₂|, |y₁ − y₂|)', useFor: 'Moves in all 8 directions, like a chess king.' },
      { name: 'Slope as an exact key', expression: '(Δy / g, Δx / g) with g = gcd(|Δy|, |Δx|), signs normalised', useFor: 'Max Points on a Line: a reduced fraction is exact where a double slope is not.' },
      { name: 'Cross product orientation', expression: '(bₓ − aₓ)(c_y − a_y) − (b_y − a_y)(cₓ − aₓ): > 0 left turn, < 0 right, 0 collinear', useFor: 'Convex hull, "are these points on one line", segment intersection.' },
      { name: 'Shoelace area', expression: '½ · |Σ (xᵢ · yᵢ₊₁ − xᵢ₊₁ · yᵢ)| over the polygon\'s vertices', useFor: 'The area of any simple polygon from its corners.' },
      { name: 'Interval overlap', expression: '[a, b] and [c, d] overlap iff max(a, c) ≤ min(b, d)', useFor: 'The one comparison behind every intervals problem.' },
      { name: 'Rectangle overlap', expression: 'overlap iff the x-intervals overlap AND the y-intervals overlap', useFor: 'The interval test, once per axis. The overlap area is the product of the two overlap lengths.' },
    ],
  },
  {
    group: 'Randomness',
    blurb: 'For the "design a data structure with getRandom()" and "pick uniformly" questions.',
    formulas: [
      { name: 'Uniform random index', expression: 'rand.nextInt(n) is uniform over 0 … n − 1', useFor: 'getRandom() in O(1) — keep the values in an array so there is something to index.' },
      { name: 'Reservoir sampling', expression: 'keep the i-th item with probability 1 / i', useFor: 'A uniform pick from a stream or linked list of unknown length, in one pass and O(1) memory.' },
      { name: 'Weighted random pick', expression: 'prefix sums of the weights, then binary-search a uniform value in [0, total)', useFor: 'Random Pick with Weight: O(n) to build, O(log n) per pick.' },
      { name: 'Fisher–Yates shuffle', expression: 'for i from n − 1 down to 1: swap(i, rand.nextInt(i + 1))', useFor: 'A uniformly random permutation in O(n). Swapping with any index instead biases it.' },
    ],
  },
];
